#include "levels/n/area_1/geo.inc.c"
#include "levels/n/area_2/geo.inc.c"
#include "levels/n/area_3/geo.inc.c"
#include "levels/n/area_4/geo.inc.c"
#include "levels/n/area_5/geo.inc.c"
#include "levels/n/area_6/geo.inc.c"
#include "levels/n/area_7/geo.inc.c"
#include "levels/n/area_0/geo.inc.c"
