extern const GeoLayout sb_train_geo[];
extern Lights1 sb_train_lotrain_lights;
extern u8 sb_train__64_rgba16[];
extern Vtx sb_train__000_farm_item_09_mesh_layer_1_vtx_0[987];
extern Gfx sb_train__000_farm_item_09_mesh_layer_1_tri_0[];
extern Vtx sb_train__000_farm_item_09_mesh_layer_1_vtx_1[61];
extern Gfx sb_train__000_farm_item_09_mesh_layer_1_tri_1[];
extern Vtx sb_train__000_farm_item_09_mesh_layer_5_vtx_0[118];
extern Gfx sb_train__000_farm_item_09_mesh_layer_5_tri_0[];
extern Gfx mat_sb_train_lotrain[];
extern Gfx mat_sb_train_light[];
extern Gfx mat_revert_sb_train_light[];
extern Gfx mat_sb_train_lightsrc[];
extern Gfx sb_train__000_farm_item_09_mesh_layer_1[];
extern Gfx sb_train__000_farm_item_09_mesh_layer_5[];
