#include "src/game/envfx_snow.h"

const GeoLayout bform5_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 78, 0, 10, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Pelvis_mesh_layer_1_mat_override_white_0),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -67, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Shell_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 53, 120, 54, 53, -34, -28),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(3, geo_update_golem_point),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -53, 120, 54, 53, 34, 28),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(4, geo_update_golem_point),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Tail_skinned_mesh_layer_1_mat_override_white_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 10, -48, 34, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Tail_mesh_layer_1_mat_override_white_0),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 45, 34, -5, -17, 0, -180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Thigh_L_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Shin_L_skinned_mesh_layer_1_mat_override_white_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Shin_L_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Foot_L_skinned_mesh_layer_1_mat_override_white_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Foot_L_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_ASM(9, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 32, 36, 83, -3, -3),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_update_golem_point),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -45, 34, -5, -17, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Thigh_R_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Shin_R_skinned_mesh_layer_1_mat_override_white_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Shin_R_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Foot_R_skinned_mesh_layer_1_mat_override_white_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Foot_R_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_ASM(8, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 32, 36, 83, 3, 3),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_update_golem_point),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Torso_skinned_mesh_layer_1_mat_override_white_0),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bform5_Torso_skinned_mesh_layer_6_mat_override_white_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, 21, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Torso_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bform5_Torso_mesh_layer_6_mat_override_white_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 44, 93, 2, -31, 0, -90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Bicept_L_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -27, 55, -2, 1, -25, 85),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(7, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Tricep_L_skinned_mesh_layer_1_mat_override_white_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform5_Tricep_L_mesh_layer_1_mat_override_white_0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 48, 0, bform5_Hand_L_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_update_sephisword),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ASM(2, geo_update_golem_part),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -44, 93, 2, -31, 0, 90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Bicept_R_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 27, 50, -5, -1, 31, -98),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(6, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform5_Tricep_R_mesh_layer_1_mat_override_white_0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bform5_Hand_R_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 38, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, -2, 7, -21, 0, -90),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(5, geo_update_golem_point),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ASM(5, geo_update_golem_part),
										GEO_CLOSE_NODE(),
										GEO_ASM(4, geo_update_golem_part),
									GEO_CLOSE_NODE(),
									GEO_ASM(1, geo_update_golem_part),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 113, 0, 33, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Head_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, bform5_Head_mesh_layer_4_mat_override_white_0),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bform5_Head_mesh_layer_5_mat_override_white_0),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Jaw_skinned_mesh_layer_1_mat_override_white_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 23, 17, -67, -180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Jaw_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, bform5_Jaw_mesh_layer_4_mat_override_white_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -8, 0, 9),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ASM(3, geo_update_golem_part),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ASM(0, geo_update_golem_part),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(0, 204, 300),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bform5_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 78, 0, 10, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Pelvis_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -67, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Shell_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 53, 120, 54, 53, -34, -28),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(3, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -53, 120, 54, 53, 34, 28),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(4, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Tail_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 10, -48, 34, 0, 180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Tail_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 45, 34, -5, -17, 0, -180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Thigh_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Shin_L_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Shin_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Foot_L_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Foot_L_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(9, geo_update_golem_point),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 32, 36, 83, -3, -3),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(2, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -45, 34, -5, -17, 0, 180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Thigh_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Shin_R_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Shin_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Foot_R_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Foot_R_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(8, geo_update_golem_point),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 32, 36, 83, 3, 3),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_update_golem_point),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Torso_skinned_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bform5_Torso_skinned_mesh_layer_6),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, 21, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Torso_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bform5_Torso_mesh_layer_6),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 44, 93, 2, -31, 0, -90),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Bicept_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -27, 55, -2, 1, -25, 85),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(7, geo_update_golem_point),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Tricep_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform5_Tricep_L_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 48, 0, bform5_Hand_L_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_update_sephisword),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ASM(2, geo_update_golem_part),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -44, 93, 2, -31, 0, 90),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Bicept_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 27, 50, -5, -1, 31, -98),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(6, geo_update_golem_point),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform5_Tricep_R_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bform5_Hand_R_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 38, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, -2, 7, -21, 0, -90),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(5, geo_update_golem_point),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ASM(5, geo_update_golem_part),
												GEO_CLOSE_NODE(),
												GEO_ASM(4, geo_update_golem_part),
											GEO_CLOSE_NODE(),
											GEO_ASM(1, geo_update_golem_part),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 113, 0, 33, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Head_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, bform5_Head_mesh_layer_4),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bform5_Head_mesh_layer_5),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform5_Jaw_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 23, 17, -67, -180, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform5_Jaw_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, bform5_Jaw_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 83, 0, -8, 0, 9),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_update_golem_point),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ASM(3, geo_update_golem_part),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ASM(0, geo_update_golem_part),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_SHADOW(0, 204, 300),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, bform5_switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
