extern const GeoLayout e_key_yellow_collect_geo[];
extern u8 e_key_yellow_collect_BasicGlow_2048_ia16[];
extern u8 e_key_yellow_collect_GlowRing_ia16[];
extern Vtx e_key_yellow_collect_b1_dl_mesh_layer_6_vtx_0[5];
extern Gfx e_key_yellow_collect_b1_dl_mesh_layer_6_tri_0[];
extern Vtx e_key_yellow_collect_b3_glow_mesh_layer_5_vtx_0[5];
extern Gfx e_key_yellow_collect_b3_glow_mesh_layer_5_tri_0[];
extern Gfx mat_e_key_yellow_collect_glow_floor_f3d[];
extern Gfx mat_revert_e_key_yellow_collect_glow_floor_f3d[];
extern Gfx mat_e_key_yellow_collect_glow_f3d[];
extern Gfx mat_revert_e_key_yellow_collect_glow_f3d[];
extern Gfx e_key_yellow_collect_b1_dl_mesh_layer_6[];
extern Gfx e_key_yellow_collect_b3_glow_mesh_layer_5[];
extern Gfx e_key_yellow_collect_material_revert_render_settings[];
