extern const GeoLayout turret_panel_geo[];
extern Lights1 turret_panel_f3dlite_material_018_lights;
extern u8 turret_panel_turret_panel_ci8[];
extern u8 turret_panel_turret_panel_pal_rgba16[];
extern Vtx turret_panel_turret_panel_mesh_layer_1_vtx_0[12];
extern Gfx turret_panel_turret_panel_mesh_layer_1_tri_0[];
extern Gfx mat_turret_panel_f3dlite_material_018[];
extern Gfx mat_revert_turret_panel_f3dlite_material_018[];
extern Gfx turret_panel_turret_panel_mesh_layer_1[];
extern Gfx turret_panel_material_revert_render_settings[];
