#include "src/game/envfx_snow.h"

const GeoLayout J_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Barrier_Station_to_Bell_Tower_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Barrier_Station_to_Bell_Tower_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Barrier_Station_to_Bell_Tower_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Barrier_Station_to_Bell_Tower_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Bell_Tower_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Burned_Tower_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_007_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_008_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_009_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_010_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_012_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_013_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Cube_014_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_003_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_004_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_005_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_006_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_007_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_008_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_009_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_010_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Cylinder_011_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_Building_1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_Building_1_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_Building_1_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_Building_1_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_Entryway_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_House_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_City_House_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Ecruteak_Gym_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Ecruteak_Gym_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Foutain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Gate_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Gate_2_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Kimono_Dance_Theater_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Kimono_Dance_Theater_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_PokeMart__Ecruteak_City__mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Pokemart_Sign__ADD_ROTATION__mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Pokemon_Center__Ecruteak_City__mesh_layer_1),
		GEO_ASM(0, e__shotgun_effects),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Terrain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, J_dl_Terrain_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_Terrain_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_Terrain_002_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout J_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_ECRUTEAK, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, J_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, J_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, J_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, J_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
