#include "src/game/envfx_snow.h"

const GeoLayout kdixie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_ALPHA, 0, 212, 0, kdixie_body_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_head_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 187, 94, kdixie_head_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, kdixie_head_mesh_layer_6),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 47, -13, kdixie_hairBase_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_hairFirst_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 6, -63, kdixie_hairFirst_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_hairSecond_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, -1, -155, kdixie_hairSecond_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_hairThird_skinned_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, -157, kdixie_hairThird_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_mouth_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, -17, 67, kdixie_mouth_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftShoulder_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 66, 165, 41, kdixie_leftShoulder_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftElbow_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 109, -13, 0, kdixie_leftElbow_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftWrist_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 91, -3, -9, kdixie_leftWrist_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftKnuckles_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 74, -1, 0, kdixie_leftKnuckles_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightShoulder_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, -67, 165, 49, kdixie_rightShoulder_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightElbow_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -109, -13, -15, kdixie_rightElbow_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightWrist_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -91, -3, -1, kdixie_rightWrist_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightKnuckles_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -74, -1, 0, kdixie_rightKnuckles_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_ALPHA, 47, 212, 0, kdixie_leftHip_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, 29, -80, -17, kdixie_leftKnee_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftFoot_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -9, -62, 12, kdixie_leftFoot_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_ALPHA, -48, 212, 0, kdixie_rightHip_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_ALPHA, -28, -80, -17, kdixie_rightKnee_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightFoot_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 9, -62, 11, kdixie_rightFoot_mesh_layer_4),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
