#include "src/game/envfx_snow.h"

const GeoLayout kdixie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_ALPHA, 0, 74, 0, kdixie_body_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_head_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 65, 33, kdixie_head_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, kdixie_head_mesh_layer_6),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 16, -5, kdixie_hairBase_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_hairFirst_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 2, -22, kdixie_hairFirst_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_hairSecond_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, -54, kdixie_hairSecond_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_hairThird_skinned_mesh_layer_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, -55, kdixie_hairThird_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_mouth_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, -6, 23, kdixie_mouth_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftHip_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 16, 0, 0, kdixie_leftHip_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftKnee_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 10, -28, -6, kdixie_leftKnee_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftFoot_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -3, -22, 4, kdixie_leftFoot_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftShoulder_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 23, 58, 14, kdixie_leftShoulder_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftElbow_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 38, -5, 0, kdixie_leftElbow_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftWrist_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 32, -1, -3, kdixie_leftWrist_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_leftKnuckles_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 26, 0, 0, kdixie_leftKnuckles_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightHip_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, -17, 0, 0, kdixie_rightHip_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightKnee_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -10, -28, -6, kdixie_rightKnee_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightFoot_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 3, -22, 4, kdixie_rightFoot_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightShoulder_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, -23, 58, 17, kdixie_rightShoulder_mesh_layer_4),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightElbow_skinned_mesh_layer_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, -38, -5, -5, kdixie_rightElbow_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightWrist_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, -32, -1, 0, kdixie_rightWrist_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, kdixie_rightKnuckles_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, -26, 0, 0, kdixie_rightKnuckles_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
