extern const GeoLayout samplesphere_geo[];
extern Lights1 samplesphere_Material1_f3d_lights;
extern Lights1 samplesphere_Material2_f3d_lights;
extern u8 samplesphere_Material1_rgba16[];
extern u8 samplesphere_Material2_rgba16[];
extern Vtx samplesphere_RollBall_mesh_layer_5_vtx_0[71];
extern Gfx samplesphere_RollBall_mesh_layer_5_tri_0[];
extern Vtx samplesphere_RollBall_mesh_layer_5_vtx_1[269];
extern Gfx samplesphere_RollBall_mesh_layer_5_tri_1[];
extern Gfx mat_samplesphere_Material1_f3d[];
extern Gfx mat_samplesphere_Material2_f3d[];
extern Gfx samplesphere_RollBall_mesh_layer_5[];
extern Gfx samplesphere_material_revert_render_settings[];
