extern const GeoLayout star_piece_geo[];
extern u8 star_piece_star_texture_ci8[];
extern u8 star_piece_star_texture_pal_rgba16[];
extern Vtx star_piece_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx star_piece_Cube_mesh_layer_1_vtx_0[66];
extern Gfx star_piece_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_star_piece_f3dlite_material[];
extern Gfx mat_revert_star_piece_f3dlite_material[];
extern Gfx star_piece_Cube_mesh_layer_1[];
extern Gfx star_piece_material_revert_render_settings[];
