#include "src/game/envfx_snow.h"

const GeoLayout g_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, e__shotgun_effects),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -3532, 879, -2882, 0, 45, 0, g_dl_debris_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_debris_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3532, 879, -2882, 0, 45, 0, g_dl_debris_solid_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, g_dl_ignoreCol_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_ignoreCol_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, g_dl_ignoreCol_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, g_dl_ignoreCol_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_Plane_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, g_dl_Plane_001_mesh_layer_5),
		GEO_ASM(0, e__shotgun_effects),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout g_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_PURPLE_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, g_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
