#include "src/game/envfx_snow.h"

const GeoLayout k_bartender_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, k_bartender_root_mesh_layer_1_mat_override_bareye2_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_upper_skinned_mesh_layer_1_mat_override_bareye2_0),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 45, 0, k_bartender_upper_mesh_layer_1_mat_override_bareye2_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_forearm_L_skinned_mesh_layer_1_mat_override_bareye2_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 69, 37, -7, -90, -90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, k_bartender_forearm_L_mesh_layer_1_mat_override_bareye2_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_arm_L_skinned_mesh_layer_1_mat_override_bareye2_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 59, 0, 0, -173, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, k_bartender_arm_L_mesh_layer_1_mat_override_bareye2_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_forearm_R_skinned_mesh_layer_1_mat_override_bareye2_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 69, -37, -90, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, k_bartender_forearm_R_mesh_layer_1_mat_override_bareye2_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_arm_R_skinned_mesh_layer_1_mat_override_bareye2_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 59, 0, k_bartender_arm_R_mesh_layer_1_mat_override_bareye2_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 81, 0, k_bartender_head_mesh_layer_1_mat_override_bareye2_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout k_bartender_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 0, 0, k_bartender_root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_upper_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 45, 0, k_bartender_upper_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_forearm_L_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 69, 37, -7, -90, -90),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, k_bartender_forearm_L_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_arm_L_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 59, 0, 0, -173, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, k_bartender_arm_L_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_forearm_R_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 69, -37, -90, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, k_bartender_forearm_R_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, k_bartender_arm_R_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 59, 0, k_bartender_arm_R_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 81, 0, k_bartender_head_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, k_bartender_switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
