extern const GeoLayout ink_test_area_1_geo[];
extern const GeoLayout ink_test_area_1[];
extern const Collision ink_test_area_1_collision[];
extern const MacroObject ink_test_area_1_macro_objs[];
extern Lights1 ink_test_dl_Placeholder_lights;
extern u8 ink_test_dl_placeholder_texture_i8[];
extern Vtx ink_test_dl_Cube_mesh_layer_1_vtx_0[90];
extern Gfx ink_test_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ink_test_dl_Cube_mesh_layer_1_vtx_1[85];
extern Gfx ink_test_dl_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_ink_test_dl_Placeholder[];
extern Gfx mat_ink_test_dl_Placeholder_ink[];
extern Gfx ink_test_dl_Cube_mesh_layer_1[];
extern Gfx ink_test_dl_material_revert_render_settings[];
