extern const GeoLayout m_bossplatform_geo[];
extern Lights1 m_bossplatform_Steel_block_Shaded_lights;
extern u8 m_bossplatform_steel_block_8_ci4[];
extern u8 m_bossplatform_steel_block_8_pal_rgba16[];
extern u8 m_bossplatform_skul_ia8[];
extern Vtx m_bossplatform_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx m_bossplatform_Cube_002_mesh_layer_1_tri_0[];
extern Vtx m_bossplatform_Cube_002_mesh_layer_6_vtx_0[4];
extern Gfx m_bossplatform_Cube_002_mesh_layer_6_tri_0[];
extern Gfx mat_m_bossplatform_Steel_block_Shaded[];
extern Gfx mat_revert_m_bossplatform_Steel_block_Shaded[];
extern Gfx mat_m_bossplatform_skul[];
extern Gfx mat_revert_m_bossplatform_skul[];
extern Gfx m_bossplatform_Cube_002_mesh_layer_1[];
extern Gfx m_bossplatform_Cube_002_mesh_layer_6[];
