#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/B/leveldata.inc.c"

#include "levels/B/bigdaddy/model.inc.c"
#include "levels/B/floaty/model.inc.c"
#include "levels/B/floaty/collision.inc.c"
#include "levels/B/little_sister/model.inc.c"
#include "levels/B/gauge/model.inc.c"
#include "levels/B/gauge/anims/data.inc.c"
#include "levels/B/gauge/anims/table.inc.c"
#include "levels/B/gauge/collision.inc.c"
#include "levels/B/waterfall/model.inc.c"
#include "levels/B/waterfall/collision.inc.c"