#include "src/game/envfx_snow.h"

const GeoLayout chaingun_guy_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chaingun_guy_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, chaingun_guy_root_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_al_skinned_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, chaingun_guy_al_skinned_mesh_layer_4),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 47, 156, -2, chaingun_guy_al_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, chaingun_guy_al_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_ar_skinned_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, chaingun_guy_ar_skinned_mesh_layer_4),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -47, 156, -2, chaingun_guy_ar_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, chaingun_guy_ar_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 3, -57, 45, chaingun_guy_g_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, chaingun_guy_g_mesh_layer_6),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 164, -7, chaingun_guy_h_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_ll_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 84, -10, chaingun_guy_ll_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_ll2_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -36, -5, chaingun_guy_ll2_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_lr_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -20, 84, -10, chaingun_guy_lr_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_lr2_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -36, -5, chaingun_guy_lr2_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(1, 128, 200),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, chaingun_guy_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, chaingun_guy_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, chaingun_guy_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
