extern const GeoLayout m_classc_switch_opt1[];
extern const GeoLayout m_classc_switch_opt2[];
extern const GeoLayout m_classc_geo[];
extern Lights1 m_classc_metal_lights;
extern Lights1 m_classc_metal2_lights;
extern u8 m_classc_rgba16_anonmoose_envmap_silver1_i8[];
extern Vtx m_classc_dl_mesh_layer_1_vtx_0[215];
extern Gfx m_classc_dl_mesh_layer_1_tri_0[];
extern Vtx m_classc_dl_mesh_layer_1_vtx_1[32];
extern Gfx m_classc_dl_mesh_layer_1_tri_1[];
extern Vtx m_classc_dl_mesh_layer_1_vtx_2[500];
extern Gfx m_classc_dl_mesh_layer_1_tri_2[];
extern Gfx mat_m_classc_metal[];
extern Gfx mat_revert_m_classc_metal[];
extern Gfx mat_m_classc_metal2[];
extern Gfx mat_revert_m_classc_metal2[];
extern Gfx mat_m_classc_redlight[];
extern Gfx mat_m_classc_nolight[];
extern Gfx mat_m_classc_white[];
extern Gfx m_classc_dl_mesh_layer_1[];
extern Gfx m_classc_dl_mesh_layer_1_mat_override_nolight_0[];
extern Gfx m_classc_dl_mesh_layer_1_mat_override_white_1[];
