#include "src/game/envfx_snow.h"

const GeoLayout bc_bowsf2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 78, 0, 10, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Pelvis_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -67, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Shell_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Tail_skinned_mesh_layer_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 10, -48, 34, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Tail_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 45, 34, -5, -17, 0, -180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Thigh_L_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Shin_L_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Shin_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Foot_L_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Foot_L_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -45, 34, -5, -17, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Thigh_R_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Shin_R_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Shin_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Foot_R_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Foot_R_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Torso_skinned_mesh_layer_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, 21, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 44, 93, 2, -31, 0, -90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Bicept_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Tricep_L_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bc_bowsf2_Tricep_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Hand_L_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bc_bowsf2_Hand_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Middle_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -9, 42, -5, bc_bowsf2_Middle_L_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Pinky_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -19, 37, -18, bc_bowsf2_Pinky_L_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Pointer_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 42, 12, bc_bowsf2_Pointer_L_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Thumb_L_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 23, 22, 13, 6, -1, -8),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Thumb_L_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -44, 93, 2, -31, 0, 90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Bicept_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Tricep_R_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bc_bowsf2_Tricep_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Hand_R_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bc_bowsf2_Hand_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Middle_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 9, 42, -5, bc_bowsf2_Middle_R_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Pinky_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 37, -18, bc_bowsf2_Pinky_R_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Pointer_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 42, 12, bc_bowsf2_Pointer_R_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Thumb_R_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -23, 22, 13, 6, 1, 8),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Thumb_R_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 113, 0, 27, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Head_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, bc_bowsf2_Head_mesh_layer_4),
									GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bc_bowsf2_Head_mesh_layer_2),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_bowsf2_Jaw_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 20, -73, -180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_bowsf2_Jaw_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, bc_bowsf2_Jaw_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(0, 204, 300),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
