#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/bowser_course/leveldata.inc.c"

#include "levels/bowser_course/matplatform/model.inc.c"
#include "levels/bowser_course/bc_tilting/model.inc.c"
#include "levels/bowser_course/bc_tilting/collision.inc.c"
#include "levels/bowser_course/bc_waddle_dee/model.inc.c"
#include "levels/bowser_course/bc_waddle_dee/anims/data.inc.c"
#include "levels/bowser_course/bc_waddle_dee/anims/table.inc.c"
#include "levels/bowser_course/bc_jelly/anims/data.inc.c"
#include "levels/bowser_course/bc_jelly/anims/table.inc.c"
#include "levels/bowser_course/bc_jelly/model.inc.c"
#include "levels/bowser_course/bc_hoodmonger/model.inc.c"
#include "levels/bowser_course/bc_hoodmonger/anims/data.inc.c"
#include "levels/bowser_course/bc_hoodmonger/anims/table.inc.c"
#include "levels/bowser_course/bc_hoodmonger_bullet/model.inc.c"
#include "levels/bowser_course/bc_fspinner/model.inc.c"
#include "levels/bowser_course/bc_fspinner/collision.inc.c"
#include "levels/bowser_course/bc_stair/model.inc.c"
#include "levels/bowser_course/bc_stair/collision.inc.c"
#include "levels/bowser_course/bc_stair_2/model.inc.c"
#include "levels/bowser_course/mverses_sky/model.inc.c"
#include "levels/bowser_course/bc_shooter/model.inc.c"
#include "levels/bowser_course/bowser_f_bullet/model.inc.c"
#include "levels/bowser_course/bc_skiploom/model.inc.c"
#include "levels/bowser_course/bc_skiploom/anims/data.inc.c"
#include "levels/bowser_course/bc_skiploom/anims/table.inc.c"
#include "levels/bowser_course/bc_atreus/model.inc.c"