#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/a/header.h"


#include "levels/a/geo.inc.c"

#include "levels/a/jelly/geo.inc.c"
#include "levels/a/jfplatform/geo.inc.c"
#include "levels/a/taxistop/geo.inc.c"
#include "levels/a/boat/geo.inc.c"
#include "levels/a/tikibox/geo.inc.c"
#include "levels/a/tramp/geo.inc.c"
#include "levels/a/floating_checker_platform/geo.inc.c"
#include "levels/a/kingjelly/geo.inc.c"
#include "levels/a/kingjellyshock/geo.inc.c"
#include "levels/a/bh_red_button/geo.inc.c"
#include "levels/a/jellys/geo.inc.c"
#include "levels/a/kktable/geo.inc.c"
#include "levels/a/kkb/geo.inc.c"
#include "levels/a/squidward/geo.inc.c"
#include "levels/a/bhbridge/geo.inc.c"
#include "levels/a/a_plank/geo.inc.c"
#include "levels/a/goodrop/geo.inc.c"
#include "levels/a/a_cage/geo.inc.c"
#include "levels/a/kingjellywave/geo.inc.c"
#include "levels/a/a_ufo_robot/geo.inc.c"
#include "levels/a/a_ham_robot/geo.inc.c"
#include "levels/a/a_launched_box/geo.inc.c"
#include "levels/a/a_robot_launcher/geo.inc.c"
#include "levels/a/dog_robot/geo.inc.c"
#include "levels/a/gas_cloud/geo.inc.c"
#include "levels/a/chained_cage/geo.inc.c"