#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/a/leveldata.inc.c"

#include "levels/a/jelly/model.inc.c"
#include "levels/a/jelly/anims/data.inc.c"
#include "levels/a/jelly/anims/table.inc.c"
#include "levels/a/jfplatform/model.inc.c"
#include "levels/a/jfplatform/collision.inc.c"
#include "levels/a/taxistop/model.inc.c"
#include "levels/a/taxistop/collision.inc.c"
#include "levels/a/boat/model.inc.c"
#include "levels/a/boat/anims/data.inc.c"
#include "levels/a/boat/anims/table.inc.c"
#include "levels/a/tikibox/model.inc.c"
#include "levels/a/tikibox/collision.inc.c"
#include "levels/a/tramp/model.inc.c"
#include "levels/a/tramp/collision.inc.c"
#include "levels/a/floating_checker_platform/model.inc.c"
#include "levels/a/floating_checker_platform/collision.inc.c"
#include "levels/a/floating_checker_platform/anims/data.inc.c"
#include "levels/a/floating_checker_platform/anims/table.inc.c"
#include "levels/a/kingjelly/model.inc.c"
#include "levels/a/kingjelly/anims/data.inc.c"
#include "levels/a/kingjelly/anims/table.inc.c"
#include "levels/a/kingjellyshock/model.inc.c"
#include "levels/a/bh_red_button/model.inc.c"
#include "levels/a/jellys/model.inc.c"