#include "src/game/envfx_snow.h"

const GeoLayout hoodoo_sorcerer_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, hoodoo_sorcerer_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 60, 0, hoodoo_sorcerer_knot_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 45, 0, hoodoo_sorcerer_body_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_head_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 226, 0, hoodoo_sorcerer_head_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, hoodoo_sorcerer_head_mesh_layer_5),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_Bone_004_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 91, 0, hoodoo_sorcerer_Bone_004_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_left_shoulder_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 29, 226, -9, hoodoo_sorcerer_left_shoulder_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_left_elbow_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 130, -9, 0, hoodoo_sorcerer_left_elbow_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 61, -2, 0, hoodoo_sorcerer_letf_wrist_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_right_shoulder_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -29, 226, -9, hoodoo_sorcerer_right_shoulder_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_right_elbow_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -130, -9, 0, hoodoo_sorcerer_right_elbow_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -61, -2, 0, hoodoo_sorcerer_right_wrist_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, hoodoo_sorcerer_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, hoodoo_sorcerer_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
