#include "src/game/envfx_snow.h"

const GeoLayout g_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, e__shotgun_effects),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_Plane_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, g_dl_Plane_002_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 984, 1070, -1598, 0, 5, 0, g_dl_Plane_005_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 984, 1376, -1598, 0, 29, 0, g_dl_Plane_006_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 483, 1075, -1314, 0, 53, 0, g_dl_Plane_007_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, g_dl_Plane_008_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, g_dl_Plane_008_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_Plane_008_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 3319, 1035, 1125, 0, 44, 0, g_dl_Plane_009_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -1331, 1017, -2248, 0, 53, 0, g_dl_Plane_010_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3042, 2838, -6690, 0, 53, 0, g_dl_Plane_011_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_Plane_013_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 73, 2763, -10196, 0, 53, 0, g_dl_Plane_017_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 736, 2763, -9696, 0, 19, 0, g_dl_Plane_019_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2663, 2730, -2446, 0, 19, 0, g_dl_Plane_020_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout g_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_PURPLE_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, g_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, g_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, g_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, g_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
