#include "anim_dance1.inc.c"
#include "anim_dance2.inc.c"
#include "anim_mariokdance.inc.c"
#include "anim_birddance.inc.c"
#include "anim_ArmatureAction_001.inc.c"
#include "anim_guitarAnimation.inc.c"
