#include "src/game/envfx_snow.h"

const GeoLayout kingjelly_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 15, 0, 0, -90, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_b1_mesh_layer_1_mat_override_WhiteBlink_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_b2_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 35, 0, kingjelly_b2_mesh_layer_1_mat_override_WhiteBlink_0),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -75, -6, 0, 23, 27, -37),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_cape3_mesh_layer_1_mat_override_WhiteBlink_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_cape2_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12, -30, 8, -7, -22, 28),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_cape2_mesh_layer_1_mat_override_WhiteBlink_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_cape1_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, -35, 0, -1, -5, 5),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_cape1_mesh_layer_1_mat_override_WhiteBlink_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 46, 0, kingjelly_crown_mesh_layer_1_mat_override_WhiteBlink_0),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 20, -1, 27, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t1_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t2_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t2_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 20, -1, -27, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t3_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t4_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t4_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -20, -1, 27, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t5_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t6_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t6_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -20, -1, -27, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t7_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t8_skinned_mesh_layer_1_mat_override_WhiteBlink_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t8_mesh_layer_1_mat_override_WhiteBlink_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout kingjelly_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 15, 0, 0, -90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_b1_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_b2_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 35, 0, kingjelly_b2_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -75, -6, 0, 23, 27, -37),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_cape3_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_cape2_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12, -30, 8, -7, -22, 28),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_cape2_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_cape1_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, -35, 0, -1, -5, 5),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_cape1_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 46, 0, kingjelly_crown_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 20, -1, 27, 180, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t1_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t2_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t2_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 20, -1, -27, 180, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t3_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t4_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t4_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -20, -1, 27, 180, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t5_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t6_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t6_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -20, -1, -27, 180, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, kingjelly_t7_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_t8_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, kingjelly_t8_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, kingjelly_switch_opt1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, kingjelly_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
