#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "level_pipe/geo.inc.c"
#include "ability_unlock/geo.inc.c"
#include "ability_sign/geo.inc.c"
#include "mario_k/geo.inc.c"
#include "cutter_blade/geo.inc.c"
#include "cutter_hand/geo.inc.c"
#include "cutter_hat/geo.inc.c"
#include "cutter_blast/geo.inc.c"
#include "cutter_particle_slash/geo.inc.c"
#include "dragonite/geo.inc.c"
#include "nitro/geo.inc.c"
#include "samplesphere/geo.inc.c"
#include "rocket_hand/geo.inc.c"
#include "rocket_button_off/geo.inc.c"
#include "rocket_button_on/geo.inc.c"
#include "squid/geo.inc.c"
#include "knight_mario/geo.inc.c"

#include "pt_mb/geo.inc.c"
#include "aim_f/geo.inc.c"
