extern const GeoLayout dbp_Bone_opt1[];
extern const GeoLayout dbp_Bone_opt2[];
extern const GeoLayout dbp_Bone_opt3[];
extern const GeoLayout dbp_geo[];
extern u8 dbp_db_particle_0_rgba16_ci4[];
extern u8 dbp_db_particle_0_rgba16_pal_rgba16[];
extern u8 dbp_db_particle_1_rgba16_ci4[];
extern u8 dbp_db_particle_1_rgba16_pal_rgba16[];
extern u8 dbp_db_particle_2_rgba16_ci4[];
extern u8 dbp_db_particle_2_rgba16_pal_rgba16[];
extern u8 dbp_db_particle_3_rgba16_ci4[];
extern u8 dbp_db_particle_3_rgba16_pal_rgba16[];
extern Vtx dbp_root_mesh_layer_4_vtx_0[4];
extern Gfx dbp_root_mesh_layer_4_tri_0[];
extern Gfx mat_dbp_db_1[];
extern Gfx mat_revert_dbp_db_1[];
extern Gfx mat_dbp_db_2[];
extern Gfx mat_revert_dbp_db_2[];
extern Gfx mat_dbp_db_3[];
extern Gfx mat_revert_dbp_db_3[];
extern Gfx mat_dbp_db_4[];
extern Gfx mat_revert_dbp_db_4[];
extern Gfx dbp_root_mesh_layer_4[];
extern Gfx dbp_root_mesh_layer_4_mat_override_db_2_0[];
extern Gfx dbp_root_mesh_layer_4_mat_override_db_3_1[];
extern Gfx dbp_root_mesh_layer_4_mat_override_db_4_2[];
extern Gfx dbp_material_revert_render_settings[];
