extern const GeoLayout o_speaker_3_geo[];
extern Lights1 o_speaker_3_Speaker1_lights;
extern Lights1 o_speaker_3_SpeakerGuts_lights;
extern u8 o_speaker_3_rgba16_anonmoose_envmap_silver1_i8[];
extern u8 o_speaker_3_speakerguts_rgba16[];
extern Vtx o_speaker_3_Cube_002_mesh_layer_1_vtx_0[82];
extern Gfx o_speaker_3_Cube_002_mesh_layer_1_tri_0[];
extern Vtx o_speaker_3_Cube_002_mesh_layer_1_vtx_1[78];
extern Gfx o_speaker_3_Cube_002_mesh_layer_1_tri_1[];
extern Vtx o_speaker_3_Cube_002_mesh_layer_1_vtx_2[27];
extern Gfx o_speaker_3_Cube_002_mesh_layer_1_tri_2[];
extern Gfx mat_o_speaker_3_Speaker1[];
extern Gfx mat_o_speaker_3_Speaker2[];
extern Gfx mat_revert_o_speaker_3_Speaker2[];
extern Gfx mat_o_speaker_3_SpeakerGuts[];
extern Gfx o_speaker_3_Cube_002_mesh_layer_1[];
extern Gfx o_speaker_3_material_revert_render_settings[];
