extern const GeoLayout cutter_blade_geo[];
extern u8 cutter_blade_shinycutter_rgba16[];
extern u8 cutter_blade_shiny_ia8[];
extern Vtx cutter_blade_Plane_mesh_layer_1_vtx_0[180];
extern Gfx cutter_blade_Plane_mesh_layer_1_tri_0[];
extern Vtx cutter_blade_Plane_mesh_layer_1_vtx_1[72];
extern Gfx cutter_blade_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_cutter_blade_f3dlite_material[];
extern Gfx mat_revert_cutter_blade_f3dlite_material[];
extern Gfx mat_cutter_blade_f3dlite_material_001[];
extern Gfx mat_revert_cutter_blade_f3dlite_material_001[];
extern Gfx cutter_blade_Plane_mesh_layer_1[];
extern Gfx cutter_blade_material_revert_render_settings[];
