#include "levels/l/area_1/geo.inc.c"
#include "levels/l/area_2/geo.inc.c"
#include "levels/l/area_3/geo.inc.c"
#include "levels/l/area_4/geo.inc.c"
#include "levels/l/area_5/geo.inc.c"
#include "levels/l/area_6/geo.inc.c"
