#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/l/leveldata.inc.c"

#include "levels/l/ptbg/model.inc.c"
#include "levels/l/johnp/model.inc.c"
#include "levels/l/lportal/model.inc.c"
#include "levels/l/l_johnblock/model.inc.c"
#include "levels/l/johnblock/collision.inc.c"
#include "levels/l/johnp/anims/data.inc.c"
#include "levels/l/johnp/anims/table.inc.c"
#include "levels/l/cheeseslime/model.inc.c"
#include "levels/l/cheeseslime/anims/data.inc.c"
#include "levels/l/cheeseslime/anims/table.inc.c"
#include "levels/l/pepperman/anims/data.inc.c"
#include "levels/l/pepperman/anims/table.inc.c"
#include "levels/l/pepperman/model.inc.c"
#include "levels/l/cbmeter/model.inc.c"
#include "levels/l/cbg/model.inc.c"
#include "levels/l/lclock/model.inc.c"
#include "levels/l/lclock/anims/data.inc.c"
#include "levels/l/lclock/anims/table.inc.c"