#include "src/game/envfx_snow.h"

const GeoLayout bform4_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 78, 0, 10, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Pelvis_mesh_layer_1_mat_override_white_0),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -67, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Shell_mesh_layer_1_mat_override_white_0),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Tail_skinned_mesh_layer_1_mat_override_white_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 10, -48, 34, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Tail_mesh_layer_1_mat_override_white_0),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 45, 34, -5, -17, 0, -180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thigh_L_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Shin_L_skinned_mesh_layer_1_mat_override_white_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Shin_L_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Foot_L_skinned_mesh_layer_1_mat_override_white_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Foot_L_mesh_layer_1_mat_override_white_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -45, 34, -5, -17, 0, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thigh_R_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Shin_R_skinned_mesh_layer_1_mat_override_white_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Shin_R_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Foot_R_skinned_mesh_layer_1_mat_override_white_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Foot_R_mesh_layer_1_mat_override_white_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Torso_skinned_mesh_layer_1_mat_override_white_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, 21, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Torso_mesh_layer_1_mat_override_white_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, bform4_Torso_mesh_layer_4_mat_override_white_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 44, 93, 2, -31, 0, -90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Bicept_L_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Tricep_L_skinned_mesh_layer_1_mat_override_white_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform4_Tricep_L_mesh_layer_1_mat_override_white_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Hand_L_skinned_mesh_layer_1_mat_override_white_0),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bform4_Hand_L_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Middle_L_skinned_mesh_layer_1_mat_override_white_0),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -9, 42, -5, bform4_Middle_L_mesh_layer_1_mat_override_white_0),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pinky_L_skinned_mesh_layer_1_mat_override_white_0),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -19, 37, -18, bform4_Pinky_L_mesh_layer_1_mat_override_white_0),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pointer_L_skinned_mesh_layer_1_mat_override_white_0),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 42, 12, bform4_Pointer_L_mesh_layer_1_mat_override_white_0),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Thumb_L_skinned_mesh_layer_1_mat_override_white_0),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 23, 22, 13, 6, -1, -8),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thumb_L_mesh_layer_1_mat_override_white_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -44, 93, 2, -31, 0, 90),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Bicept_R_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Tricep_R_skinned_mesh_layer_1_mat_override_white_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform4_Tricep_R_mesh_layer_1_mat_override_white_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Hand_R_skinned_mesh_layer_1_mat_override_white_0),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bform4_Hand_R_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Middle_R_skinned_mesh_layer_1_mat_override_white_0),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 9, 42, -5, bform4_Middle_R_mesh_layer_1_mat_override_white_0),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pinky_R_skinned_mesh_layer_1_mat_override_white_0),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 37, -18, bform4_Pinky_R_mesh_layer_1_mat_override_white_0),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pointer_R_skinned_mesh_layer_1_mat_override_white_0),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 42, 12, bform4_Pointer_R_mesh_layer_1_mat_override_white_0),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Thumb_R_skinned_mesh_layer_1_mat_override_white_0),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -23, 22, 13, 6, 1, 8),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thumb_R_mesh_layer_1_mat_override_white_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 113, 0, 27, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Head_mesh_layer_1_mat_override_white_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, bform4_Head_mesh_layer_4_mat_override_white_0),
									GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bform4_Head_mesh_layer_2_mat_override_white_0),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Jaw_skinned_mesh_layer_1_mat_override_white_0),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 20, -73, -180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Jaw_mesh_layer_1_mat_override_white_0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, bform4_Jaw_mesh_layer_4_mat_override_white_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(0, 204, 300),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bform4_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 78, 0, 10, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Pelvis_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -67, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Shell_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Tail_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 10, -48, 34, 0, 180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Tail_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 45, 34, -5, -17, 0, -180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thigh_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Shin_L_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Shin_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Foot_L_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Foot_L_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -45, 34, -5, -17, 0, 180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thigh_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Shin_R_skinned_mesh_layer_1),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 46, 0, -14, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Shin_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Foot_R_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 54, 0, 97, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Foot_R_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Torso_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, 21, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Torso_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, bform4_Torso_mesh_layer_4),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 44, 93, 2, -31, 0, -90),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Bicept_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Tricep_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform4_Tricep_L_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Hand_L_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bform4_Hand_L_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Middle_L_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, -9, 42, -5, bform4_Middle_L_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pinky_L_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, -19, 37, -18, bform4_Pinky_L_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pointer_L_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 42, 12, bform4_Pointer_L_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Thumb_L_skinned_mesh_layer_1),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 23, 22, 13, 6, -1, -8),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thumb_L_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -44, 93, 2, -31, 0, 90),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Bicept_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Tricep_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 67, 0, bform4_Tricep_R_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Hand_R_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 37, 0, bform4_Hand_R_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Middle_R_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 9, 42, -5, bform4_Middle_R_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pinky_R_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 37, -18, bform4_Pinky_R_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Pointer_R_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 1, 42, 12, bform4_Pointer_R_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Thumb_R_skinned_mesh_layer_1),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -23, 22, 13, 6, 1, 8),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Thumb_R_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 113, 0, 27, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Head_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, bform4_Head_mesh_layer_4),
											GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, bform4_Head_mesh_layer_2),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, bform4_Jaw_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 20, -73, -180, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bform4_Jaw_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, bform4_Jaw_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_SHADOW(0, 204, 300),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, bform4_switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
