extern const GeoLayout bc_stair_2_geo[];
extern Lights1 bc_stair_2_startile_001_layer1_lights;
extern u8 bc_stair_2_startile_i8[];
extern u8 bc_stair_2_subtle_rainboo_rgba16[];
extern Vtx bc_stair_2_Plane_009_mesh_layer_1_vtx_0[6];
extern Gfx bc_stair_2_Plane_009_mesh_layer_1_tri_0[];
extern Gfx mat_bc_stair_2_startile_001_layer1[];
extern Gfx mat_revert_bc_stair_2_startile_001_layer1[];
extern Gfx bc_stair_2_Plane_009_mesh_layer_1[];
extern Gfx bc_stair_2_material_revert_render_settings[];
