extern const GeoLayout wooden_lever_geo[];
extern Lights1 wooden_lever_f3dlite_material_001_lights;
extern u8 wooden_lever_lever2_ci8[];
extern u8 wooden_lever_lever2_pal_rgba16[];
extern Vtx wooden_lever_levier_mesh_layer_1_vtx_0[148];
extern Gfx wooden_lever_levier_mesh_layer_1_tri_0[];
extern Gfx mat_wooden_lever_f3dlite_material_001[];
extern Gfx mat_revert_wooden_lever_f3dlite_material_001[];
extern Gfx wooden_lever_levier_mesh_layer_1[];
extern Gfx wooden_lever_material_revert_render_settings[];
