extern const GeoLayout flipswitch1_geo[];
extern u8 flipswitch1_rgba16_anonmoose_envmap_silver1_i8[];
extern u8 flipswitch1_red_switch_ci8[];
extern u8 flipswitch1_red_switch_pal_rgba16[];
extern Vtx flipswitch1_Cube_001_mesh_layer_1_vtx_0[26];
extern Gfx flipswitch1_Cube_001_mesh_layer_1_tri_0[];
extern Vtx flipswitch1_Cube_001_mesh_layer_1_vtx_1[29];
extern Gfx flipswitch1_Cube_001_mesh_layer_1_tri_1[];
extern Gfx mat_flipswitch1_metal[];
extern Gfx mat_revert_flipswitch1_metal[];
extern Gfx mat_flipswitch1_button_active[];
extern Gfx mat_revert_flipswitch1_button_active[];
extern Gfx flipswitch1_Cube_001_mesh_layer_1[];
extern Gfx flipswitch1_material_revert_render_settings[];
