#include "src/game/envfx_snow.h"

const GeoLayout castle_inside_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 5782, 2658, -5383, 90, 0, 0, castle_inside_dl_Area3Vis_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, castle_inside_dl_Area3Vis_001_mesh_layer_2),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 748, 810, -55, castle_inside_dl_Buildings_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE_DECAL, 748, 810, -55, castle_inside_dl_Buildings_002_mesh_layer_2),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Buildings_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2318, 1931, -5757, -1, 8, 20, castle_inside_dl_Circle_077_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 2242, 1612, 1511, castle_inside_dl_creditsslab_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1372, 1612, 2321, castle_inside_dl_Cube_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Cube_001_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Cube_001_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -5952, 2893, 5379, castle_inside_dl_Cube_003_mesh_layer_1),
		GEO_ASM(0, geo_update_hub_sky),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -5118, 1994, -2127, castle_inside_dl_kirby_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -5118, 1994, -2127, castle_inside_dl_kirby_001_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -4989, 2126, 2039, 90, 0, 0, castle_inside_dl_level_c_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_level_c_001_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -8342, 2658, 93, 90, 0, 0, castle_inside_dl_machine_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_machine_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_machine_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -23111, 1976, -6961, 0, -135, 0, castle_inside_dl_main_section_geo_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Map_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Map_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Map_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 8146, 3327, -225, castle_inside_dl_model_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 8146, 3327, -225, castle_inside_dl_model_001_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_model_001_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_model_001_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_model_001_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -5347, 2658, 5280, castle_inside_dl_Plane_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -5966, 2658, 5850, castle_inside_dl_Plane_001_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -6088, 2658, 5308, castle_inside_dl_Plane_002_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -6340, 2658, 5098, castle_inside_dl_Plane_003_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_ALPHA, -2594, 2711, -5729, -70, -84, -88, castle_inside_dl_Plane_040_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1093, -169, -8060, castle_inside_dl_Plane_047_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -4956, 7158, 7006, castle_inside_dl_ptower_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_ptower_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1960, 1612, -919, 90, 0, 80, castle_inside_dl_redd_tent_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_Room_1_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_Room_1_002_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 6632, 2658, 5771, castle_inside_dl_Route42_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Route42_001_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 6632, 2658, 5771, castle_inside_dl_Route42_002_mesh_layer_4),
		GEO_ASM(0, e__shotgun_effects),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 5043, 615, 1533, castle_inside_dl_SkyScaper_046_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -2592, 2699, -5730, 70, 96, 88, castle_inside_dl_Torus_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -1845, -2310, -4053, 90, 0, 0, castle_inside_dl_Tropical_Island_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_Tropical_Island_001_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 6478, 2658, 3645, castle_inside_dl_visual_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 748, 810, -55, 748, 710, -55, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_inside_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
