#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/e/header.h"


#include "levels/e/geo.inc.c"

#include "levels/e/caco/geo.inc.c"
#include "levels/e/caco_2/geo.inc.c"
#include "levels/e/temp_fire/geo.inc.c"
#include "levels/e/e_door/geo.inc.c"
#include "levels/e/e_key_blue/geo.inc.c"
#include "levels/e/e_key_red/geo.inc.c"
#include "levels/e/e_key_yellow/geo.inc.c"
#include "levels/e/e_key_yellow_collect/geo.inc.c"
#include "levels/e/e_key_red_collect/geo.inc.c"
#include "levels/e/e_key_blue_collect/geo.inc.c"
#include "levels/e/e_elevator/geo.inc.c"
#include "levels/e/e_elevator_base/geo.inc.c"
#include "levels/e/e_candelabra/geo.inc.c"
#include "levels/e/e_switch/geo.inc.c"
#include "levels/e/e_switch2/geo.inc.c"
#include "levels/e/e_teleport/geo.inc.c"
#include "levels/e/e_teleport_effect/geo.inc.c"
#include "levels/e/e_door_c/geo.inc.c"
#include "levels/e/e_door_c_d/geo.inc.c"

#include "levels/e/pistol_guy/geo.inc.c"
#include "levels/e/chaingun_guy/geo.inc.c"
#include "levels/e/e_medkit/geo.inc.c"
#include "levels/e/e_medkit_effect/geo.inc.c"
#include "levels/e/e_shells/geo.inc.c"

#include "levels/e/e_c9_muzzle_flash/geo.inc.c"
#include "levels/e/e_red_door_candle/geo.inc.c"
#include "levels/e/e_candelabra_o/geo.inc.c"
#include "levels/e/e_t1/geo.inc.c"
#include "levels/e/e_t2/geo.inc.c"
#include "levels/e/e_t3/geo.inc.c"
#include "levels/e/e_tb/geo.inc.c"
#include "levels/e/e_secret_door/geo.inc.c"