#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/e/leveldata.inc.c"

#include "levels/e/caco/model.inc.c"
#include "levels/e/caco/anims/data.inc.c"
#include "levels/e/caco/anims/table.inc.c"
#include "levels/e/caco_2/model.inc.c"
#include "levels/e/temp_fire/model.inc.c"
#include "levels/e/e_door/model.inc.c"
#include "levels/e/e_door/collision.inc.c"
#include "levels/e/e_key_blue/model.inc.c"
#include "levels/e/e_key_red/model.inc.c"
#include "levels/e/e_key_yellow/model.inc.c"
#include "levels/e/e_key_yellow_collect/model.inc.c"
#include "levels/e/e_key_red_collect/model.inc.c"
#include "levels/e/e_key_blue_collect/model.inc.c"
#include "levels/e/e_elevator/model.inc.c"
#include "levels/e/e_elevator/collision.inc.c"
#include "levels/e/e_elevator_base/collision.inc.c"
#include "levels/e/e_elevator_base/model.inc.c"
#include "levels/e/e_candelabra/model.inc.c"
#include "levels/e/e_switch/model.inc.c"
#include "levels/e/e_switch/collision.inc.c"
#include "levels/e/e_switch2/model.inc.c"
#include "levels/e/e_teleport/model.inc.c"
#include "levels/e/e_teleport/collision.inc.c"
#include "levels/e/e_teleport_effect/model.inc.c"
#include "levels/e/e_door_light/model.inc.c"
#include "levels/e/e_door_c/model.inc.c"
#include "levels/e/e_door_c_d/model.inc.c"
#include "levels/e/e_hud/model.inc.c"
#include "levels/e/e_hud_m/model.inc.c"
#include "levels/e/e_bullet/model.inc.c"
#include "levels/e/e_caco_fb/model.inc.c"

#include "levels/e/pistol_guy/model.inc.c"
#include "levels/e/pistol_guy/anims/data.inc.c"
#include "levels/e/pistol_guy/anims/table.inc.c"
#include "levels/e/chaingun_guy/model.inc.c"
#include "levels/e/chaingun_guy/anims/data.inc.c"
#include "levels/e/chaingun_guy/anims/table.inc.c"
#include "levels/e/e_medkit/model.inc.c"
#include "levels/e/e_medkit_effect/model.inc.c"
#include "levels/e/e_shells/model.inc.c"
#include "levels/e/e_sky/model.inc.c"

#include "levels/e/e_c9_muzzle_flash/model.inc.c"
#include "levels/e/e_red_door_candle/model.inc.c"
#include "levels/e/e_candelabra_o/model.inc.c"
#include "levels/e/e_t1/model.inc.c"
#include "levels/e/e_t2/model.inc.c"
#include "levels/e/e_t3/model.inc.c"
#include "levels/e/e_tb/collision.inc.c"
#include "levels/e/e_tb/model.inc.c"
#include "levels/e/e_secret_door/model.inc.c"