#include "src/game/envfx_snow.h"

const GeoLayout checkpoint_flag_switchcase_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1, 82, 0, -1, 0, 91),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, checkpoint_flag_f1_mesh_layer_5_mat_override_flag1_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, checkpoint_flag_f2_skinned_mesh_layer_5_mat_override_flag1_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 30, 0, 0, -1, -1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, checkpoint_flag_f2_mesh_layer_5_mat_override_flag1_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, checkpoint_flag_f3_skinned_mesh_layer_5_mat_override_flag1_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 27, 0, checkpoint_flag_f3_mesh_layer_5_mat_override_flag1_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout checkpoint_flag_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, checkpoint_flag_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(2, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -1, 82, 0, -1, 0, 91),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, checkpoint_flag_f1_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, checkpoint_flag_f2_skinned_mesh_layer_5),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 30, 0, 0, -1, -1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, checkpoint_flag_f2_mesh_layer_5),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, checkpoint_flag_f3_skinned_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 27, 0, checkpoint_flag_f3_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, checkpoint_flag_switchcase_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, checkpoint_flag_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, checkpoint_flag_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
