extern const GeoLayout hub_target_box_Bone_002_opt1[];
extern const GeoLayout hub_target_box_geo[];
extern Lights1 hub_target_box_f3dlite_material_002_lights;
extern Lights1 hub_target_box_target_orange_lights;
extern Lights1 hub_target_box_f3dlite_material_003_lights;
extern u8 hub_target_box_frame16_ci4[];
extern u8 hub_target_box_frame16_pal_rgba16[];
extern u8 hub_target_box_target16_ci4[];
extern u8 hub_target_box_target16_pal_rgba16[];
extern u8 hub_target_box_green_target16_ci4[];
extern u8 hub_target_box_green_target16_pal_rgba16[];
extern Vtx hub_target_box_Bone_mesh_layer_4_vtx_0[24];
extern Gfx hub_target_box_Bone_mesh_layer_4_tri_0[];
extern Vtx hub_target_box_Bone_004_mesh_layer_1_vtx_0[59];
extern Gfx hub_target_box_Bone_004_mesh_layer_1_tri_0[];
extern Gfx mat_hub_target_box_f3dlite_material_002[];
extern Gfx mat_revert_hub_target_box_f3dlite_material_002[];
extern Gfx mat_hub_target_box_target_orange[];
extern Gfx mat_revert_hub_target_box_target_orange[];
extern Gfx mat_hub_target_box_f3dlite_material_003[];
extern Gfx mat_revert_hub_target_box_f3dlite_material_003[];
extern Gfx hub_target_box_Bone_mesh_layer_4[];
extern Gfx hub_target_box_Bone_004_mesh_layer_1[];
extern Gfx hub_target_box_Bone_004_mesh_layer_1_mat_override_f3dlite_material_003_0[];
