#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/k/leveldata.inc.c"

#include "levels/k/ksky/model.inc.c"
#include "levels/k/k_strong_terry/model.inc.c"
#include "levels/k/k_fan/model.inc.c"
#include "levels/k/k_fan/collision.inc.c"
#include "levels/k/k_fan_2/collision.inc.c"
#include "levels/k/k_blood/model.inc.c"
#include "levels/k/kaguya/model.inc.c"
#include "levels/k/k_disco/model.inc.c"
#include "levels/k/k_bartender/model.inc.c"
#include "levels/k/k_bartender/anims/data.inc.c"
#include "levels/k/k_bartender/anims/table.inc.c"
#include "levels/k/k_blood2/model.inc.c"
#include "levels/k/electrohead/model.inc.c"
#include "levels/k/k_tv1/model.inc.c"
#include "levels/k/k_tv2/model.inc.c"
#include "levels/k/k_tv3/model.inc.c"
#include "levels/k/k_tv4/model.inc.c"
#include "levels/k/k_lite/model.inc.c"
#include "levels/k/k_pounder/model.inc.c"
#include "levels/k/k_pounder/collision.inc.c"
#include "levels/k/k_skinny_ricky/model.inc.c"
#include "levels/k/k_slight/model.inc.c"
#include "levels/k/k_shieldo/model.inc.c"
#include "levels/k/kbul/model.inc.c"
#include "levels/k/k_josh/model.inc.c"
#include "levels/k/kdancer/anims/data.inc.c"
#include "levels/k/kdancer/anims/table.inc.c"