#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/k/leveldata.inc.c"

#include "levels/k/ksky/model.inc.c"
#include "levels/k/k_strong_terry/model.inc.c"
#include "levels/k/k_fan/model.inc.c"
#include "levels/k/k_fan/collision.inc.c"
#include "levels/k/k_fan_2/collision.inc.c"
#include "levels/k/k_blood/model.inc.c"
#include "levels/k/kaguya/model.inc.c"
#include "levels/k/k_disco/model.inc.c"
#include "levels/k/k_bartender/model.inc.c"
#include "levels/k/k_bartender/anims/data.inc.c"
#include "levels/k/k_bartender/anims/table.inc.c"