extern void scroll_k_dl_Cube_002_mesh_layer_1_vtx_1();
extern void scroll_k_dl_z_mesh_layer_5_vtx_0();
extern void scroll_k_dl_room_mesh_layer_1_vtx_0();
extern void scroll_k_dl_room_mesh_layer_1_vtx_4();
extern void scroll_gfx_mat_k_dl_rainbowlight();
extern void scroll_gfx_mat_k_dl_rainbowlight_op();
extern void scroll_gfx_mat_k_dl_FloorGlow();
extern void scroll_gfx_mat_k_dl_Floor();
extern void scroll_k();
