#include "src/game/envfx_snow.h"

const GeoLayout redd_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 24, 0, redd_base_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Lfoot1_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 11, 0, 0, redd_Lfoot1_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Lfoot2_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -12, 0, redd_Lfoot2_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Rfoot1_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -11, 0, 0, redd_Rfoot1_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Rfoot2_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -12, 0, redd_Rfoot2_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_chest_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 27, 0, redd_chest_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Larm1_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 21, 0, redd_Larm1_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Larm2_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 16, 0, 0, redd_Larm2_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Rarm1_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -18, 21, 0, redd_Rarm1_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_Rarm2_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -16, 0, 0, redd_Rarm2_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 31, 0, redd_head_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_mouth_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 55, 0, -90, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, redd_mouth_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_tail1_skinned_mesh_layer_1),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 6, -23, 0, 90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, redd_tail1_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, redd_tail2_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 3, 0, redd_tail2_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
