#include "src/game/envfx_snow.h"

const GeoLayout k_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 136, 1655, -5196, 0, -180, 0, k_dl_0diamondrenderfirst_mesh_layer_5),
		GEO_ASM(0, geo_update_k_rainbow_triangles),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 136, 1655, -5196, 0, -180, 0, k_dl_afloor_renderfirst_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, k_dl_afloor_renderfirst_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 136, 1655, -5196, 0, -180, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_colorful_env),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, k_dl_envstuff_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, k_dl_envstuff_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 136, 1655, -5196, 0, -180, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_colorful_env_lite),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, k_dl_liteenvstuff_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, k_dl_liteenvstuff_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, k_dl_liteenvstuff_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 136, 1655, -5196, 0, -180, 0, k_dl_visual_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, k_dl_visual_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 136, 1655, -5196, 0, -180, 0, k_dl_z_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 802, 1810, -2941, k_dl_zalchohol_render_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, k_dl_zalchohol_render_mesh_layer_7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout k_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, k_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
