#include "levels/J/area_0/geo.inc.c"
#include "levels/J/area_2/geo.inc.c"
#include "levels/J/area_3/geo.inc.c"
#include "levels/J/area_4/geo.inc.c"
#include "levels/J/area_1/geo.inc.c"
#include "levels/J/area_5/geo.inc.c"
#include "levels/J/area_6/geo.inc.c"
#include "levels/J/area_7/geo.inc.c"
