extern const GeoLayout o_area_1_geo[];
extern const GeoLayout o_area_1[];
extern const Collision o_area_1_collision[];
extern const MacroObject o_area_1_macro_objs[];
extern Lights1 o_dl_f3dlite_material_lights;
extern Lights1 o_dl_uvtutorial_lights;
extern u8 o_dl_koura_ci8[];
extern u8 o_dl_koura_pal_rgba16[];
extern u8 o_dl_uvtutorial_ia4[];
extern Vtx o_dl_Cube_mesh_layer_1_vtx_0[346];
extern Gfx o_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx o_dl_uvlight_mesh_layer_5_vtx_0[40];
extern Gfx o_dl_uvlight_mesh_layer_5_tri_0[];
extern Gfx mat_o_dl_f3dlite_material[];
extern Gfx mat_revert_o_dl_f3dlite_material[];
extern Gfx mat_o_dl_uvtutorial[];
extern Gfx o_dl_Cube_mesh_layer_1[];
extern Gfx o_dl_uvlight_mesh_layer_5[];
extern Gfx o_dl_material_revert_render_settings[];
