#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/o/leveldata.inc.c"

#include "levels/o/o_zombie1/model.inc.c"
#include "levels/o/o_zombie/anims/data.inc.c"
#include "levels/o/o_zombie/anims/table.inc.c"
#include "levels/o/o_zombie2/model.inc.c"
#include "levels/o/o_zombie3/model.inc.c"
#include "levels/o/o_zomblood/model.inc.c"
#include "levels/o/o_tree/model.inc.c"
#include "levels/o/o_uvstar/model.inc.c"
#include "levels/o/o_lift/model.inc.c"
#include "levels/o/o_lift/collision.inc.c"
#include "levels/o/o_spooky_sky/model.inc.c"
#include "levels/o/o_garage/model.inc.c"
#include "levels/o/o_garage/collision.inc.c"
#include "levels/o/o_speaker_1/model.inc.c"
#include "levels/o/o_speaker_2/model.inc.c"
#include "levels/o/o_speaker_3/model.inc.c"
#include "levels/o/o_flame/model.inc.c"
#include "levels/o/o_gerik/model.inc.c"