extern const GeoLayout windmill_geo[];
extern u8 windmill_manche_ci4[];
extern u8 windmill_manche_pal_rgba16[];
extern u8 windmill_toile1_ci4[];
extern u8 windmill_toile1_pal_rgba16[];
extern Vtx windmill_moulin_mesh_layer_5_vtx_0[40];
extern Gfx windmill_moulin_mesh_layer_5_tri_0[];
extern Vtx windmill_moulin_mesh_layer_5_vtx_1[18];
extern Gfx windmill_moulin_mesh_layer_5_tri_1[];
extern Gfx mat_windmill_f3dlite_material_001[];
extern Gfx mat_revert_windmill_f3dlite_material_001[];
extern Gfx mat_windmill_f3dlite_material[];
extern Gfx mat_revert_windmill_f3dlite_material[];
extern Gfx windmill_moulin_mesh_layer_5[];
extern Gfx windmill_material_revert_render_settings[];
