#include "levels/m/area_1/collision.inc.c"
#include "levels/m/area_1/macro.inc.c"
#include "levels/m/area_1/spline.inc.c"
#include "levels/m/area_4/collision.inc.c"
#include "levels/m/area_4/room.inc.c"
#include "levels/m/area_4/macro.inc.c"
#include "levels/m/area_4/spline.inc.c"
#include "levels/m/model.inc.c"
