#include "src/game/envfx_snow.h"

const GeoLayout mumbo_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -180, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mumbo_Bone_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 84, 0, mumbo_Bone_001_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 94, 0, mumbo_Bone_002_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mumbo_Bone_002_mesh_layer_4),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_004_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -24, 65, -6, mumbo_Bone_004_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_007_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -17, -32, -14, mumbo_Bone_007_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_011_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -8, -3, -25, mumbo_Bone_011_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_005_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 34, 65, 0, mumbo_Bone_005_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_008_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 24, -22, -21, mumbo_Bone_008_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_010_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 6, 0, -24, mumbo_Bone_010_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mumbo_Bone_006_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -39, 0, -22, mumbo_Bone_006_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
