#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/g/header.h"


#include "levels/g/geo.inc.c"

#include "levels/g/sir_kibble/geo.inc.c"
#include "levels/g/star_block/geo.inc.c"
#include "levels/g/star_projectile/geo.inc.c"
#include "levels/g/checker_block_1/geo.inc.c"
#include "levels/g/g_spring/geo.inc.c"
#include "levels/g/g_cut_rock/geo.inc.c"
#include "levels/g/g_cut_rock2/geo.inc.c"
#include "levels/g/g_cut_rock3/geo.inc.c"
#include "levels/g/g_cannon/geo.inc.c"
#include "levels/g/marx/geo.inc.c"
#include "levels/g/g_marx_cutter/geo.inc.c"
#include "levels/g/g_marx_seed/geo.inc.c"
#include "levels/g/g_marx_thorn/geo.inc.c"
#include "levels/g/g_marx_right_half/geo.inc.c"
#include "levels/g/g_marx_left_half/geo.inc.c"
#include "levels/g/g_marx_black_hole/geo.inc.c"
#include "levels/g/g_marx_arrow/geo.inc.c"
#include "levels/g/g_marx_mouth_full/geo.inc.c"
#include "levels/g/g_marx_mouth_open/geo.inc.c"
#include "levels/g/g_marx_laser/geo.inc.c"
#include "levels/g/g_marx_ice_bomb/geo.inc.c"
#include "levels/g/g_marx_ice_ring/geo.inc.c"
#include "levels/g/g_marx_black_hole_effect/geo.inc.c"
#include "levels/g/g_bronto_burt/geo.inc.c"
#include "levels/g/g_moving_platform/geo.inc.c"
#include "levels/g/g_marx_door/geo.inc.c"