extern const GeoLayout g_area_1_geo[];
extern const GeoLayout g_area_1[];
extern const Collision g_area_1_collision[];
extern const MacroObject g_area_1_macro_objs[];
extern const GeoLayout g_area_2_geo[];
extern const GeoLayout g_area_2[];
extern const Collision g_area_2_collision[];
extern const MacroObject g_area_2_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint g_area_2_spline_KibbleFocus[];
extern Lights1 g_dl_f3dlite_material_011_lights;
extern u8 g_dl_dreamlandfringe_ia8[];
extern u8 g_dl_altgrass_rgba16[];
extern u8 g_dl_grass_ci8[];
extern u8 g_dl_grass_pal_rgba16[];
extern u8 g_dl_happy_eorpe_ci8[];
extern u8 g_dl_happy_eorpe_pal_rgba16[];
extern u8 g_dl_Frushedwater_i4[];
extern u8 g_dl_fwater_i4[];
extern u8 g_dl_path_ci8[];
extern u8 g_dl_path_pal_rgba16[];
extern u8 g_dl_groundstardecal_ia4[];
extern u8 g_dl_dreamlandstone_ia8[];
extern u8 g_dl_stardecal_ia4[];
extern u8 g_dl_altstone_ia8[];
extern u8 g_dl_innerwallstardecal_ia4[];
extern u8 g_dl_bridge_ci4[];
extern u8 g_dl_bridge_pal_rgba16[];
extern u8 g_dl_imgonline_com_ua_TextureSeamless_i6bhGHkEXWAW_rgba16[];
extern u8 g_dl_succulent_looking_tile_ci8[];
extern u8 g_dl_succulent_looking_tile_pal_rgba16[];
extern u8 g_dl_starblock_ci4[];
extern u8 g_dl_starblock_pal_rgba16[];
extern u8 g_dl_plank_ci8[];
extern u8 g_dl_plank_pal_rgba16[];
extern Vtx g_dl_ignoreCol_mesh_layer_6_vtx_0[190];
extern Gfx g_dl_ignoreCol_mesh_layer_6_tri_0[];
extern Vtx g_dl_ignoreCol_mesh_layer_4_vtx_0[48];
extern Gfx g_dl_ignoreCol_mesh_layer_4_tri_0[];
extern Vtx g_dl_ignoreCol_mesh_layer_4_vtx_1[94];
extern Gfx g_dl_ignoreCol_mesh_layer_4_tri_1[];
extern Vtx g_dl_ignoreCol_mesh_layer_5_vtx_0[15];
extern Gfx g_dl_ignoreCol_mesh_layer_5_tri_0[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_0[74];
extern Gfx g_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_1[167];
extern Gfx g_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_2[207];
extern Gfx g_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_3[188];
extern Gfx g_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_4[166];
extern Gfx g_dl_Plane_mesh_layer_1_tri_4[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_5[59];
extern Gfx g_dl_Plane_mesh_layer_1_tri_5[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_6[108];
extern Gfx g_dl_Plane_mesh_layer_1_tri_6[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_7[120];
extern Gfx g_dl_Plane_mesh_layer_1_tri_7[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_8[192];
extern Gfx g_dl_Plane_mesh_layer_1_tri_8[];
extern Vtx g_dl_Plane_001_mesh_layer_5_vtx_0[28];
extern Gfx g_dl_Plane_001_mesh_layer_5_tri_0[];
extern Vtx g_dl_Circle_mesh_layer_1_vtx_0[233];
extern Gfx g_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx g_dl_Circle_mesh_layer_1_vtx_1[27];
extern Gfx g_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx g_dl_Circle_mesh_layer_1_vtx_2[8];
extern Gfx g_dl_Circle_mesh_layer_1_tri_2[];
extern Gfx mat_g_dl_f3dlite_material_001_layer6[];
extern Gfx mat_revert_g_dl_f3dlite_material_001_layer6[];
extern Gfx mat_g_dl_f3dlite_material_002[];
extern Gfx mat_revert_g_dl_f3dlite_material_002[];
extern Gfx mat_g_dl_f3dlite_material_005[];
extern Gfx mat_revert_g_dl_f3dlite_material_005[];
extern Gfx mat_g_dl_cozieswater_001_layer5_area1[];
extern Gfx mat_revert_g_dl_cozieswater_001_layer5_area1[];
extern Gfx mat_g_dl_f3dlite_material_004[];
extern Gfx mat_revert_g_dl_f3dlite_material_004[];
extern Gfx mat_g_dl_grass_layer1[];
extern Gfx mat_revert_g_dl_grass_layer1[];
extern Gfx mat_g_dl_outerwallstone_layer1[];
extern Gfx mat_revert_g_dl_outerwallstone_layer1[];
extern Gfx mat_g_dl_force_push_layer1[];
extern Gfx mat_revert_g_dl_force_push_layer1[];
extern Gfx mat_g_dl_bridhe[];
extern Gfx mat_revert_g_dl_bridhe[];
extern Gfx mat_g_dl_outerwallstonetextured_layer1[];
extern Gfx mat_revert_g_dl_outerwallstonetextured_layer1[];
extern Gfx mat_g_dl_f3dlite_material_007[];
extern Gfx mat_revert_g_dl_f3dlite_material_007[];
extern Gfx mat_g_dl_f3dlite_material[];
extern Gfx mat_revert_g_dl_f3dlite_material[];
extern Gfx mat_g_dl_f3dlite_material_006[];
extern Gfx mat_revert_g_dl_f3dlite_material_006[];
extern Gfx mat_g_dl_s[];
extern Gfx mat_revert_g_dl_s[];
extern Gfx mat_g_dl_f3dlite_material_011[];
extern Gfx mat_g_dl_starr_door[];
extern Gfx mat_revert_g_dl_starr_door[];
extern Gfx g_dl_ignoreCol_mesh_layer_6[];
extern Gfx g_dl_ignoreCol_mesh_layer_4[];
extern Gfx g_dl_ignoreCol_mesh_layer_5[];
extern Gfx g_dl_Plane_mesh_layer_1[];
extern Gfx g_dl_Plane_001_mesh_layer_5[];
extern Gfx g_dl_Circle_mesh_layer_1[];
extern Gfx g_dl_material_revert_render_settings[];
