extern const GeoLayout g_area_1_geo[];
extern const GeoLayout g_area_1[];
extern const Collision g_area_1_collision[];
extern const MacroObject g_area_1_macro_objs[];
extern Lights1 g_dl_f3dlite_material_001_layer1_lights;
extern u8 g_dl_dreamlandfringe_ia8[];
extern u8 g_dl_altgrass_rgba16[];
extern u8 g_dl_altstone_ia8[];
extern u8 g_dl_stardecal_ia4[];
extern Vtx g_dl_ignoreCol_mesh_layer_1_vtx_0[8];
extern Gfx g_dl_ignoreCol_mesh_layer_1_tri_0[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_0[309];
extern Gfx g_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx g_dl_Plane_mesh_layer_1_vtx_1[132];
extern Gfx g_dl_Plane_mesh_layer_1_tri_1[];
extern Gfx mat_g_dl_f3dlite_material_001_layer1[];
extern Gfx mat_revert_g_dl_f3dlite_material_001_layer1[];
extern Gfx mat_g_dl_f3dlite_material_003[];
extern Gfx mat_revert_g_dl_f3dlite_material_003[];
extern Gfx mat_g_dl_f3dlite_material_layer1[];
extern Gfx mat_revert_g_dl_f3dlite_material_layer1[];
extern Gfx g_dl_ignoreCol_mesh_layer_1[];
extern Gfx g_dl_Plane_mesh_layer_1[];
extern Gfx g_dl_material_revert_render_settings[];
