#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/g/leveldata.inc.c"

#include "levels/g/sir_kibble/model.inc.c"
#include "levels/g/sir_kibble/anims/data.inc.c"
#include "levels/g/sir_kibble/anims/table.inc.c"
#include "levels/g/star_block/model.inc.c"
#include "levels/g/star_projectile/model.inc.c"
#include "levels/g/checker_block_1/model.inc.c"
#include "levels/g/checker_block_1/collision.inc.c"
#include "levels/g/g_spring/model.inc.c"
#include "levels/g/g_spring/collision.inc.c"
#include "levels/g/g_cut_rock/model.inc.c"
#include "levels/g/g_cut_rock/collision.inc.c"
#include "levels/g/g_cut_rock2/model.inc.c"
#include "levels/g/g_cut_rock3/model.inc.c"