#include "src/game/envfx_snow.h"

const GeoLayout dragonite_switchcase_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -20, dragonite_Root_mesh_layer_1_mat_override_EyeClosed_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Tail1_skinned_mesh_layer_1_mat_override_EyeClosed_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 54, -36, -90, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_Tail1_mesh_layer_1_mat_override_EyeClosed_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Tail2_skinned_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, dragonite_Tail2_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Tail3_skinned_mesh_layer_1_mat_override_EyeClosed_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 137, 0, -1, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_Tail3_mesh_layer_1_mat_override_EyeClosed_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Torso_skinned_mesh_layer_1_mat_override_EyeClosed_0),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 119, 0, dragonite_Torso_mesh_layer_1_mat_override_EyeClosed_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Head_skinned_mesh_layer_1_mat_override_EyeClosed_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 112, 0, 15, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_Head_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dragonite_Head_mesh_layer_5_mat_override_EyeClosed_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 33, 62, 0, 0, 0, -90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_l_UpperArm_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_l_LowerArm_skinned_mesh_layer_1_mat_override_EyeClosed_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 49, 0, dragonite_l_LowerArm_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 32, 44, -30, 0, 32, -78),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, dragonite_l_Wing_mesh_layer_4_mat_override_EyeClosed_0),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -33, 62, 0, 0, 0, 90),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_r_UpperArm_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_r_LowerArm_skinned_mesh_layer_1_mat_override_EyeClosed_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 49, 0, dragonite_r_LowerArm_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -32, 44, -30, 0, -32, 78),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, dragonite_r_Wing_mesh_layer_4_mat_override_EyeClosed_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 65, 80, 0, 0, -90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_l_Thigh_mesh_layer_1_mat_override_EyeClosed_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_l_Foot_skinned_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 101, 0, 0, 0, 87),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_l_Foot_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -65, 80, 0, 0, 90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_r_Thigh_mesh_layer_1_mat_override_EyeClosed_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_r_Foot_skinned_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 101, 0, 0, 0, -87),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_r_Foot_mesh_layer_1_mat_override_EyeClosed_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dragonite_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -20, dragonite_Root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Tail1_skinned_mesh_layer_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 3, 54, -36, -90, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_Tail1_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Tail2_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, dragonite_Tail2_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Tail3_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 137, 0, -1, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_Tail3_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Torso_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 119, 0, dragonite_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_Head_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 112, 0, 15, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_Head_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dragonite_Head_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 33, 62, 0, 0, 0, -90),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_l_UpperArm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_l_LowerArm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 49, 0, dragonite_l_LowerArm_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 32, 44, -30, 0, 32, -78),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, dragonite_l_Wing_mesh_layer_4),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -33, 62, 0, 0, 0, 90),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_r_UpperArm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_r_LowerArm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 49, 0, dragonite_r_LowerArm_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -32, 44, -30, 0, -32, 78),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, dragonite_r_Wing_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 65, 80, 0, 0, -90, -180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_l_Thigh_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_l_Foot_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 101, 0, 0, 0, 87),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_l_Foot_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -65, 80, 0, 0, 90, 180),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_r_Thigh_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_r_Foot_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 101, 0, 0, 0, -87),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dragonite_r_Foot_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dragonite_switchcase_opt1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dragonite_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dragonite_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dragonite_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
