extern const GeoLayout k_pounder_geo[];
extern Lights1 k_pounder_caution_lights;
extern u8 k_pounder_rgba16_anonmoose_envmap_silver1_i8[];
extern u8 k_pounder_WarningTape_ci8[];
extern u8 k_pounder_WarningTape_pal_rgba16[];
extern Vtx k_pounder_Cube_mesh_layer_1_vtx_0[46];
extern Gfx k_pounder_Cube_mesh_layer_1_tri_0[];
extern Vtx k_pounder_Cube_mesh_layer_1_vtx_1[12];
extern Gfx k_pounder_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_k_pounder_clubenv_layer1[];
extern Gfx mat_revert_k_pounder_clubenv_layer1[];
extern Gfx mat_k_pounder_caution[];
extern Gfx mat_revert_k_pounder_caution[];
extern Gfx k_pounder_Cube_mesh_layer_1[];
