extern const GeoLayout f_fence_geo[];
extern u8 f_fence_Gate_Fence_ci4[];
extern u8 f_fence_Gate_Fence_pal_rgba16[];
extern u8 f_fence_Fancy_Metal_Fence_ci4[];
extern u8 f_fence_Fancy_Metal_Fence_pal_rgba16[];
extern Vtx f_fence_Gate_Fence_BEFORE_Keypad_mesh_layer_5_vtx_0[12];
extern Gfx f_fence_Gate_Fence_BEFORE_Keypad_mesh_layer_5_tri_0[];
extern Vtx f_fence_Gate_Fence_BEFORE_Keypad_mesh_layer_5_vtx_1[16];
extern Gfx f_fence_Gate_Fence_BEFORE_Keypad_mesh_layer_5_tri_1[];
extern Gfx mat_f_fence_Gate_Fence_001[];
extern Gfx mat_revert_f_fence_Gate_Fence_001[];
extern Gfx mat_f_fence_Fancy_Metal_Fence_001[];
extern Gfx mat_revert_f_fence_Fancy_Metal_Fence_001[];
extern Gfx f_fence_Gate_Fence_BEFORE_Keypad_mesh_layer_5[];
extern Gfx f_fence_material_revert_render_settings[];
