#include "src/game/envfx_snow.h"

const GeoLayout B_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, B_dl_Room_1_geo),
			GEO_BRANCH(1, B_dl_Room_2_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -258, 3373, 2221, B_dl_AAAAAAAAA_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout B_dl_Room_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -110, 939, 2757, B_dl_Room_1_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, B_dl_Room_1_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, B_dl_Room_1_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, B_dl_Room_1_mesh_layer_7),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, B_dl_Room_1_mesh_layer_6),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 110, 3042, -2757, B_dl_Ocean_mesh_layer_5),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, B_dl_Ocean_mesh_layer_7),
			GEO_CLOSE_NODE(),
			GEO_ASM(0, e__shotgun_effects),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, 110, -939, -2757),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 1611, -8055, -14720, B_dl_watertemple_collision_mesh_layer_6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout B_dl_Room_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -110, 939, 2757, B_dl_Room_2_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, B_dl_Room_2_mesh_layer_6),
			GEO_DISPLAY_LIST(LAYER_ALPHA, B_dl_Room_2_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout B_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_PARALLEL_TRACKING, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, B_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, B_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, B_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, B_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, B_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, B_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
