#include "src/game/envfx_snow.h"

const GeoLayout birthday_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -17, 359, 380, birthday_dl_Balloon_Cluster_mesh_layer_1),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -1107, -221, 403, birthday_dl_Balloon_Cluster_Flat_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -1436, -57, 74, birthday_dl_Balloon_Cluster_Flat_002_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -1436, -57, -345, birthday_dl_Balloon_Cluster_Flat_003_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -1449, 222, -792, birthday_dl_Balloon_Cluster_Flat_004_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -950, 222, -777, birthday_dl_Balloon_Cluster_Flat_005_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, -711, 222, -560, birthday_dl_Balloon_Cluster_Flat_006_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 670, 222, -553, birthday_dl_Balloon_Cluster_Flat_007_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 911, 314, -784, birthday_dl_Balloon_Cluster_Flat_008_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 1399, 316, -792, birthday_dl_Balloon_Cluster_Flat_009_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 1400, -57, -505, birthday_dl_Balloon_Cluster_Flat_010_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 1400, -57, 74, birthday_dl_Balloon_Cluster_Flat_011_mesh_layer_4),
		GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 1071, -221, 403, birthday_dl_Balloon_Cluster_Flat_012_mesh_layer_4),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -15, 258, -514, 90, 0, 0, birthday_dl_Cake_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, birthday_dl_Cake_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT_DECAL, -24, -78, -278, 0, 45, 0, birthday_dl_Decorations_mesh_layer_6),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, birthday_dl_Decorations_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, birthday_dl_Map_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, birthday_dl_Map_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, birthday_dl_Map_mesh_layer_6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout birthday_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, birthday_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
