#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/sb/leveldata.inc.c"

#include "levels/sb/sb_stairs/model.inc.c"
#include "levels/sb/sb_torch_1/model.inc.c"
#include "levels/sb/sb_torch_2/model.inc.c"
#include "levels/sb/sb_gaster/model.inc.c"
#include "levels/sb/sbsky/model.inc.c"
#include "levels/sb/sb_yukari/model.inc.c"
#include "levels/sb/sb_humanoid/anims/data.inc.c"
#include "levels/sb/sb_humanoid/anims/table.inc.c"
#include "levels/sb/sb_train/model.inc.c"
#include "levels/sb/sb_train/collision.inc.c"
#include "levels/sb/sb_gap/model.inc.c"
#include "levels/sb/sbdm/model.inc.c"
#include "levels/sb/sbdms/model.inc.c"
#include "levels/sb/sbdmk/model.inc.c"
#include "levels/sb/sb_blaster/model.inc.c"
#include "levels/sb/sb_blaster/anims/data.inc.c"
#include "levels/sb/sb_blaster/anims/table.inc.c"