extern const GeoLayout paint_gun_Bone_002_opt1[];
extern const GeoLayout paint_gun_geo[];
extern u8 paint_gun_gun_bump_i8[];
extern u8 paint_gun_bleu_ci8[];
extern u8 paint_gun_bleu_pal_rgba16[];
extern u8 paint_gun_circle_ia8[];
extern u8 paint_gun_orange_ci8[];
extern u8 paint_gun_orange_pal_rgba16[];
extern Vtx paint_gun_Bone_004_mesh_layer_1_vtx_0[168];
extern Gfx paint_gun_Bone_004_mesh_layer_1_tri_0[];
extern Vtx paint_gun_Bone_004_mesh_layer_1_vtx_1[43];
extern Gfx paint_gun_Bone_004_mesh_layer_1_tri_1[];
extern Vtx paint_gun_Bone_004_mesh_layer_5_vtx_0[4];
extern Gfx paint_gun_Bone_004_mesh_layer_5_tri_0[];
extern Gfx mat_paint_gun_f3dlite_material_006[];
extern Gfx mat_revert_paint_gun_f3dlite_material_006[];
extern Gfx mat_paint_gun_blue[];
extern Gfx mat_revert_paint_gun_blue[];
extern Gfx mat_paint_gun_f3dlite_material_005[];
extern Gfx mat_revert_paint_gun_f3dlite_material_005[];
extern Gfx mat_paint_gun_orange[];
extern Gfx mat_revert_paint_gun_orange[];
extern Gfx paint_gun_Bone_004_mesh_layer_1[];
extern Gfx paint_gun_Bone_004_mesh_layer_1_mat_override_orange_0[];
extern Gfx paint_gun_Bone_004_mesh_layer_5[];
extern Gfx paint_gun_Bone_004_mesh_layer_5_mat_override_orange_0[];
extern Gfx paint_gun_material_revert_render_settings[];
