extern const GeoLayout c_area_1_geo[];
extern const GeoLayout c_area_1[];
extern const Collision c_area_1_collision[];
extern const MacroObject c_area_1_macro_objs[];
extern Lights1 c_dl_f3dlite_material_lights;
extern u8 c_dl__0x75A0_ci4[];
extern u8 c_dl__0x75A0_pal_rgba16[];
extern u8 c_dl_sable_ci4[];
extern u8 c_dl_sable_pal_rgba16[];
extern u8 c_dl_Material1_ci8[];
extern u8 c_dl_Material1_pal_rgba16[];
extern u8 c_dl_SM64_LAST_IMPACT_3134A15C_0_2_all_i8[];
extern u8 c_dl__329B08FD44F137CC65EF2A6CFE0DB3CB_ci4[];
extern u8 c_dl__329B08FD44F137CC65EF2A6CFE0DB3CB_pal_rgba16[];
extern Vtx c_dl_level_c_mesh_layer_1_vtx_0[285];
extern Gfx c_dl_level_c_mesh_layer_1_tri_0[];
extern Vtx c_dl_level_c_mesh_layer_1_vtx_1[203];
extern Gfx c_dl_level_c_mesh_layer_1_tri_1[];
extern Vtx c_dl_level_c_mesh_layer_1_vtx_2[16];
extern Gfx c_dl_level_c_mesh_layer_1_tri_2[];
extern Vtx c_dl_level_c_mesh_layer_1_vtx_3[85];
extern Gfx c_dl_level_c_mesh_layer_1_tri_3[];
extern Vtx c_dl_level_c_mesh_layer_1_vtx_4[4];
extern Gfx c_dl_level_c_mesh_layer_1_tri_4[];
extern Gfx mat_c_dl_f3dlite_material_001[];
extern Gfx mat_revert_c_dl_f3dlite_material_001[];
extern Gfx mat_c_dl_f3dlite_material[];
extern Gfx mat_revert_c_dl_f3dlite_material[];
extern Gfx mat_c_dl_f3dlite_material_003[];
extern Gfx mat_revert_c_dl_f3dlite_material_003[];
extern Gfx mat_c_dl_f3dlite_material_002[];
extern Gfx mat_revert_c_dl_f3dlite_material_002[];
extern Gfx mat_c_dl_f3dlite_material_004[];
extern Gfx mat_revert_c_dl_f3dlite_material_004[];
extern Gfx c_dl_level_c_mesh_layer_1[];
extern Gfx c_dl_material_revert_render_settings[];
