#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/c/leveldata.inc.c"

#include "levels/c/crane_arrow/model.inc.c"
#include "levels/c/crane_arrow/collision.inc.c"
#include "levels/c/paint_gun/model.inc.c"
#include "levels/c/crane_head/model.inc.c"
#include "levels/c/crane/model.inc.c"
#include "levels/c/octoball/model.inc.c"
#include "levels/c/star_boulder/model.inc.c"
#include "levels/c/paint_stain/model.inc.c"
#include "levels/c/splat_target/model.inc.c"
#include "levels/c/target_box/model.inc.c"
#include "levels/c/target_box/collision.inc.c"
#include "levels/c/octomissile/model.inc.c"
#include "levels/c/flag/model.inc.c"
#include "levels/c/flag/anims/data.inc.c"
#include "levels/c/flag/anims/table.inc.c"
#include "levels/c/ink_moving_platform/model.inc.c"
#include "levels/c/ink_moving_platform/collision.inc.c"
#include "levels/c/paint_bullet/model.inc.c"
#include "levels/c/octozepplin/model.inc.c"
#include "levels/c/jelly_fish/model.inc.c"
#include "levels/c/jelly_fish/anims/data.inc.c"
#include "levels/c/jelly_fish/anims/table.inc.c"
#include "levels/c/octoba/model.inc.c"