extern const GeoLayout shock_rocket_geo[];
extern Lights1 rocket_hand_f3dlite_material_001_lights;
extern u8 rocket_hand_missile_ci4[];
extern u8 rocket_hand_missile_ci4_pal_rgba16[];
extern Vtx rocket_hand_RaymanMissile_mesh_layer_1_vtx_cull[8];
extern Vtx rocket_hand_RaymanMissile_mesh_layer_1_vtx_0[456];
extern Gfx rocket_hand_RaymanMissile_mesh_layer_1_tri_0[];
extern Gfx mat_rocket_hand_f3dlite_material_001[];
extern Gfx mat_revert_rocket_hand_f3dlite_material_001[];
extern Gfx rocket_hand_RaymanMissile_mesh_layer_1[];
extern Gfx rocket_hand_material_revert_render_settings[];
