const struct Animation *const humanoid_anims[] = {
	&humanoid_anim_Generic_Run,
	&humanoid_anim_idle,
	&humanoid_anim_die,
	&humanoid_anim_holdmario,
	&humanoid_anim_axehold,
	&humanoid_anim_axewalk,
	&humanoid_anim_whack,
	&humanoid_anim_terrymash,
	&humanoid_anim_stagger,
	&humanoid_anim_shieldblock,
	&humanoid_anim_shieldshoot,
	&humanoid_anim_shieldblockup,
	NULL,
};
