extern const GeoLayout g_marx_arrow_geo[];
extern u8 g_marx_arrow_marxarrow_ci4[];
extern u8 g_marx_arrow_marxarrow_pal_rgba16[];
extern Vtx g_marx_arrow_Plane_003_mesh_layer_4_vtx_cull[8];
extern Vtx g_marx_arrow_Plane_003_mesh_layer_4_vtx_0[8];
extern Gfx g_marx_arrow_Plane_003_mesh_layer_4_tri_0[];
extern Gfx mat_g_marx_arrow_f3dlite_material_022[];
extern Gfx mat_revert_g_marx_arrow_f3dlite_material_022[];
extern Gfx g_marx_arrow_Plane_003_mesh_layer_4[];
extern Gfx g_marx_arrow_material_revert_render_settings[];
