extern const GeoLayout gate_geo[];
extern Lights1 gate_f3dlite_material_lights;
extern Lights1 gate_f3dlite_material_001_lights;
extern u8 gate_metal1_ci8[];
extern u8 gate_metal1_pal_rgba16[];
extern u8 gate_metal_bar_ci8[];
extern u8 gate_metal_bar_pal_rgba16[];
extern Vtx gate_gate_mesh_layer_1_vtx_0[82];
extern Gfx gate_gate_mesh_layer_1_tri_0[];
extern Vtx gate_gate_mesh_layer_1_vtx_1[22];
extern Gfx gate_gate_mesh_layer_1_tri_1[];
extern Gfx mat_gate_f3dlite_material[];
extern Gfx mat_revert_gate_f3dlite_material[];
extern Gfx mat_gate_f3dlite_material_001[];
extern Gfx mat_revert_gate_f3dlite_material_001[];
extern Gfx gate_gate_mesh_layer_1[];
extern Gfx gate_material_revert_render_settings[];
