extern void scroll_castle_inside_dl_machine_mesh_layer_1_vtx_5();
extern void scroll_castle_inside_dl_Map_mesh_layer_1_vtx_0();
extern void scroll_castle_inside_dl_Map_mesh_layer_5_vtx_0();
extern void scroll_castle_inside_dl_Map_mesh_layer_5_vtx_1();
extern void scroll_castle_inside_dl_Room_1_002_mesh_layer_5_vtx_1();
extern void scroll_gfx_mat_castle_inside_dl_acid_f3d_layer5();
extern void scroll_gfx_mat_castle_inside_dl_waterfall_001_layer5();
extern void scroll_castle_inside();
