extern const GeoLayout megacork_geo[];
extern Lights1 megacork_cork_lights;
extern u8 megacork_sonic_adventure_dirt_32x_rgba16[];
extern u8 megacork_ground_pound_ia8[];
extern Vtx megacork_cork_mesh_layer_1_vtx_0[25];
extern Gfx megacork_cork_mesh_layer_1_tri_0[];
extern Vtx megacork_cork_mesh_layer_2_vtx_0[4];
extern Gfx megacork_cork_mesh_layer_2_tri_0[];
extern Gfx mat_megacork_cork[];
extern Gfx mat_megacork_f3dlite_material_009_layer2[];
extern Gfx mat_revert_megacork_f3dlite_material_009_layer2[];
extern Gfx megacork_cork_mesh_layer_1[];
extern Gfx megacork_cork_mesh_layer_2[];
extern Gfx megacork_material_revert_render_settings[];
