#include "levels/bowser_course/bc_bosslanding/texscroll.inc.h"
#include "levels/bowser_course/bc_atreus/texscroll.inc.h"
#include "levels/bowser_course/mverses_sky/texscroll.inc.h"
#include "levels/bowser_course/bc_stair_2/texscroll.inc.h"
#include "levels/bowser_course/bc_stair/texscroll.inc.h"
#include "levels/bowser_course/texscroll.inc.h"
#include "levels/bowser_course/matplatform/texscroll.inc.h"
#include "levels/bowser_course/sb_train/texscroll.inc.h"
#include "levels/bowser_course/sb_gap/texscroll.inc.h"
extern void scroll_textures_bowser_course();
