#include "src/game/envfx_snow.h"

const GeoLayout h_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(0, geo_update_h_sky),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 2145, 846, 2535, 90, 0, 0, h_dl_Ads_mesh_layer_1),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -11, 0, h_dl_Buildings_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -11615, 7543, -12966, 0, 15, 0, h_dl_Helios_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, h_dl_levellayou_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, h_dl_levellayou_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, h_dl_Plants_and_Fauna_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 6330, -1212, 538, h_dl_Platforms_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -4192, -3257, 12445, -90, 0, 180, h_dl_Sewers_mesh_layer_1),
		GEO_ASM(0, e__shotgun_effects),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, h_dl_SmallerBits_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, h_dl_SmallerBits_002_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout h_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 127, 65535, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, h_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, h_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, h_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
