extern const GeoLayout e_medkit_effect_geo[];
extern u8 e_medkit_effect_BasicGlow_2048_ia16[];
extern u8 e_medkit_effect_BasicGlow_2048_ia8[];
extern Vtx e_medkit_effect_b1_dl_mesh_layer_6_vtx_0[5];
extern Gfx e_medkit_effect_b1_dl_mesh_layer_6_tri_0[];
extern Vtx e_medkit_effect_b3_glow_mesh_layer_5_vtx_0[5];
extern Gfx e_medkit_effect_b3_glow_mesh_layer_5_tri_0[];
extern Gfx mat_e_medkit_effect_glow_floor_f3d[];
extern Gfx mat_revert_e_medkit_effect_glow_floor_f3d[];
extern Gfx mat_e_medkit_effect_glow_f3d[];
extern Gfx mat_revert_e_medkit_effect_glow_f3d[];
extern Gfx e_medkit_effect_b1_dl_mesh_layer_6[];
extern Gfx e_medkit_effect_b3_glow_mesh_layer_5[];
extern Gfx e_medkit_effect_material_revert_render_settings[];
