#include "src/game/envfx_snow.h"

const GeoLayout bc_hoodmonger_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_hoodmonger_Bone_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_hoodmonger_Bone_001_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 110, 0, bc_hoodmonger_Bone_001_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_hoodmonger_Bone_002_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 88, 0, bc_hoodmonger_Bone_002_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bc_hoodmonger_Bone_002_mesh_layer_5),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 55, 64, -1, bc_hoodmonger_Bone_006_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_hoodmonger_Bone_008_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -5, 0, bc_hoodmonger_Bone_008_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 80, -7, 0, bc_hoodmonger_Bone_010_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -56, 64, 0, bc_hoodmonger_Bone_007_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_hoodmonger_Bone_011_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -73, -5, 0, bc_hoodmonger_Bone_011_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -80, -7, 0, bc_hoodmonger_Bone_013_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -20, 1, -3, 0, -51, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, bc_hoodmonger_Bone_015_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bc_hoodmonger_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bc_hoodmonger_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
