extern const GeoLayout pigpot_geo[];
extern Lights1 pigpot_f3dlite_material_lights;
extern u8 pigpot_pigpot_indexed_ci4[];
extern u8 pigpot_pigpot_indexed_pal_rgba16[];
extern Vtx pigpot_pigpot_mesh_layer_1_vtx_0[135];
extern Gfx pigpot_pigpot_mesh_layer_1_tri_0[];
extern Gfx mat_pigpot_f3dlite_material[];
extern Gfx mat_revert_pigpot_f3dlite_material[];
extern Gfx pigpot_pigpot_mesh_layer_1[];
extern Gfx pigpot_material_revert_render_settings[];
