extern const GeoLayout g_marx_laser_geo[];
extern u8 g_marx_laser_marxlaser_ci4[];
extern u8 g_marx_laser_marxlaser_pal_rgba16[];
extern Vtx g_marx_laser_Circle_001_mesh_layer_1_vtx_cull[8];
extern Vtx g_marx_laser_Circle_001_mesh_layer_1_vtx_0[47];
extern Gfx g_marx_laser_Circle_001_mesh_layer_1_tri_0[];
extern Gfx mat_g_marx_laser_f3dlite_material_024[];
extern Gfx mat_revert_g_marx_laser_f3dlite_material_024[];
extern Gfx g_marx_laser_Circle_001_mesh_layer_1[];
extern Gfx g_marx_laser_material_revert_render_settings[];
