#ifndef SEQ_IDS_H
#define SEQ_IDS_H

// Sometimes a sequence id is represented as one of the below ids (the base id),
// optionally OR'd with SEQ_VARIATION.
#define SEQ_BASE_ID 0x7f
#define SEQ_VARIATION 0x80
#define SEQUENCE_NONE 0xFF

#define SEQ_MENU_GAME_OVER (SEQ_MENU_TITLE_SCREEN | SEQ_VARIATION)

enum SeqId {
    SEQ_SOUND_PLAYER,  // 0x00
    SEQ_EVENT_CUTSCENE_COLLECT_STAR,  // 0x01
    SEQ_MENU_TITLE_SCREEN,  // 0x02
    SEQ_LEVEL_GRASS,  // 0x03
    SEQ_LEVEL_INSIDE_CASTLE,  // 0x04
    SEQ_LEVEL_WATER,  // 0x05
    SEQ_LEVEL_HOT,  // 0x06
    SEQ_LEVEL_BOSS_KOOPA,  // 0x07
    SEQ_LEVEL_SNOW,  // 0x08
    SEQ_LEVEL_SLIDE,  // 0x09
    SEQ_LEVEL_SPOOKY,  // 0x0A
    SEQ_EVENT_PIRANHA_PLANT,  // 0x0B
    SEQ_LEVEL_UNDERGROUND,  // 0x0C
    SEQ_MENU_STAR_SELECT,  // 0x0D
    SEQ_EVENT_POWERUP,  // 0x0E
    SEQ_EVENT_METAL_CAP,  // 0x0F
    SEQ_EVENT_KOOPA_MESSAGE,  // 0x10
    SEQ_LEVEL_KOOPA_ROAD,  // 0x11
    SEQ_EVENT_HIGH_SCORE,  // 0x12
    SEQ_EVENT_MERRY_GO_ROUND,  // 0x13
    SEQ_EVENT_RACE,  // 0x14
    SEQ_EVENT_CUTSCENE_STAR_SPAWN,  // 0x15
    SEQ_EVENT_BOSS,  // 0x16
    SEQ_EVENT_CUTSCENE_COLLECT_KEY,  // 0x17
    SEQ_EVENT_ENDLESS_STAIRS,  // 0x18
    SEQ_LEVEL_BOSS_KOOPA_FINAL,  // 0x19
    SEQ_EVENT_CUTSCENE_CREDITS,  // 0x1A
    SEQ_EVENT_SOLVE_PUZZLE,  // 0x1B
    SEQ_EVENT_TOAD_MESSAGE,  // 0x1C
    SEQ_EVENT_PEACH_MESSAGE,  // 0x1D
    SEQ_EVENT_CUTSCENE_INTRO,  // 0x1E
    SEQ_EVENT_CUTSCENE_VICTORY,  // 0x1F
    SEQ_EVENT_CUTSCENE_ENDING,  // 0x20
    SEQ_MENU_FILE_SELECT,  // 0x21
    SEQ_EVENT_CUTSCENE_LAKITU,  // 0x22 (not in JP)
    SEQ_MATT_MONRO,
    SEQ_INRBIO,
    SEQ_CUSTOM_PEANUT_PLAINS,
    SEQ_CUSTOM_KIRBY_BOSS,
    SEQ_CUSTOM_SAVE_HUT,
    SEQ_CUSTOM_CRYSTAL_FIELD,
    SEQ_CUSTOM_TREES_IN_THE_DEPTHS,
    SEQ_CUSTOM_MARX,
    SEQ_CUSTOM_ECRUTEAK,
    SEQ_CUSTOM_AZALEA,
    SEQ_CUSTOM_UNION_CAVE,
    SEQ_CUSTOM_VS_HOOH,  // 0x2E
    SEQ_CUSTOM_GYM,
    SEQ_CUSTOM_DARK_CAVE,
    SEQ_O_EASYSTREET,  // 0x2B
    SEQ_O_MAINTRACK,  // 0x2C
    SEQ_LEVEL_I_CARRYING_THE_PLUM,
    SEQ_CLEARLEAF_FOREST,  // 0x34
    SEQ_FUNKY_SHELL,  // 0x35
    SEQ_MASTER_KAAG_BOSS,  // 0x36
    SEQ_LEVEL_I_INSIDE,  // 0X37
    SEQ_LEVEL_I_AMBUSH,
    SEQ_JELLYFISH_FIELDS,
    SEQ_JELLYFISH_SECRET,
    SEQ_H_GEOTHERMAL,
    SEQ_F_FRWL,
    SEQ_F_BOND,
    SEQ_D_OVER,
    SEQ_D_UNDER,
    SEQ_PEACHS_BIRTHDAY,
    SEQ_BOWSER_TIME,
    SEQ_L_HOT_SPAGHETTI,
    SEQ_L_MONDAYS,
    SEQ_L_PIZZA_TIME,
    SEQ_JELLYFISH_BOSS,
    SEQ_PEPPERMAN_STRIKES,
    SEQ_CUSTOM_ESA_SUBMERGED,  // 0x2D
    SEQ_CUSTOM_ESA_AMMOINEN,  // 0x2E
    SEQ_CUSTOM_ESA_VALIANT,  // 0x2F
    SEQ_DOWNTOWN_BB,
    SEQ_C_SEA_ME_NOW,
    SEQ_C9,  // 0x4C
    SEQ_MITM_FILE_SELECT,
    SEQ_MITM_HUB,
    SEQ_MITM_BOWSER_COURSE,  // 0x4F
    SEQ_MITM_GET_ABILITY,
    SEQ_K_CHINATOWN,
    SEQ_HAMSTERBALL,
    SEQ_CUSTOM_ESA_MECHA,
    SEQ_MUTECITY,
    SEQ_BIGBLUE,
    SEQ_O_STH,  // 0x56
    SEQ_MINECART_RIDING,
    SEQ_ROCKSOLID,  // 0x58
    SEQ_FINAL_BOSS,
    SEQ_C6,  // 0x5A
    SEQ_COUNT,
};

#endif // SEQ_IDS_H
