extern const GeoLayout tilty_hexagon_geo[];
extern Lights1 tilty_hexagon_Ledge_lights;
extern Lights1 tilty_hexagon_LessSlipperyRock_lights;
extern u8 tilty_hexagon_Ledge_rgba16[];
extern u8 tilty_hexagon_Dirt2_ci4[];
extern u8 tilty_hexagon_Dirt2_ci4_pal_rgba16[];
extern Vtx tilty_hexagon_TiltyHexagon_mesh_layer_1_vtx_0[42];
extern Gfx tilty_hexagon_TiltyHexagon_mesh_layer_1_tri_0[];
extern Vtx tilty_hexagon_TiltyHexagon_mesh_layer_1_vtx_1[6];
extern Gfx tilty_hexagon_TiltyHexagon_mesh_layer_1_tri_1[];
extern Gfx mat_tilty_hexagon_Ledge[];
extern Gfx mat_tilty_hexagon_LessSlipperyRock[];
extern Gfx mat_revert_tilty_hexagon_LessSlipperyRock[];
extern Gfx tilty_hexagon_TiltyHexagon_mesh_layer_1[];
extern Gfx tilty_hexagon_material_revert_render_settings[];
