extern const GeoLayout berry_geo[];
extern Lights1 berry_Berry_lights;
extern Lights1 berry_Stem_lights;
extern u8 berry_BerrySkin_ci8[];
extern u8 berry_BerrySkin_ci8_pal_rgba16[];
extern Vtx berry_Berry_mesh_layer_1_vtx_0[79];
extern Gfx berry_Berry_mesh_layer_1_tri_0[];
extern Vtx berry_Berry_mesh_layer_1_vtx_1[23];
extern Gfx berry_Berry_mesh_layer_1_tri_1[];
extern Gfx mat_berry_Berry[];
extern Gfx mat_revert_berry_Berry[];
extern Gfx mat_berry_Stem[];
extern Gfx berry_Berry_mesh_layer_1[];
extern Gfx berry_material_revert_render_settings[];
