#include "src/game/envfx_snow.h"

const GeoLayout pistol_guy_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, pistol_guy_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_al_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 33, 115, -3, pistol_guy_al_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_ar_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -33, 115, -3, pistol_guy_ar_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 4, -34, 48, pistol_guy_g_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 143, -6, pistol_guy_h_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_ll_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 18, 73, -8, pistol_guy_ll_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_ll2_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 1, -32, -4, pistol_guy_ll2_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_lr_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -18, 73, -8, pistol_guy_lr_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_lr2_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -32, -4, pistol_guy_lr2_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_SHADOW(1, 128, 150),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, pistol_guy_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
