extern const GeoLayout level_pipe_geo[];
extern Lights1 level_pipe_MversePipe1_layer1_lights;
extern u8 level_pipe_greypipe_i8[];
extern u8 level_pipe_mverse_pipe_stars_ia8[];
extern Vtx level_pipe_Level_Pipe_Visual_mesh_layer_1_vtx_0[197];
extern Gfx level_pipe_Level_Pipe_Visual_mesh_layer_1_tri_0[];
extern Vtx level_pipe_Level_Pipe_Visual_mesh_layer_1_vtx_1[256];
extern Gfx level_pipe_Level_Pipe_Visual_mesh_layer_1_tri_1[];
extern Gfx mat_level_pipe_MversePipe1_layer1[];
extern Gfx mat_revert_level_pipe_MversePipe1_layer1[];
extern Gfx mat_level_pipe_MversePipe2_layer1[];
extern Gfx mat_revert_level_pipe_MversePipe2_layer1[];
extern Gfx level_pipe_Level_Pipe_Visual_mesh_layer_1[];
extern Gfx level_pipe_material_revert_render_settings[];
