extern const GeoLayout i_area_1_geo[];
extern const GeoLayout i_area_1[];
extern const Collision i_area_1_collision[];
extern const MacroObject i_area_1_macro_objs[];
extern Lights1 i_dl_grass_lights;
extern Lights1 i_dl_wall_lights;
extern Lights1 i_dl_arbre_lights;
extern u8 i_dl_grass_ci4[];
extern u8 i_dl_grass_pal_rgba16[];
extern u8 i_dl_stone1_ci4[];
extern u8 i_dl_stone1_pal_rgba16[];
extern u8 i_dl_arbre_rgba16[];
extern Vtx i_dl_level_test1_mesh_layer_1_vtx_0[22];
extern Gfx i_dl_level_test1_mesh_layer_1_tri_0[];
extern Vtx i_dl_level_test1_mesh_layer_1_vtx_1[24];
extern Gfx i_dl_level_test1_mesh_layer_1_tri_1[];
extern Vtx i_dl_level_test1_mesh_layer_1_vtx_2[24];
extern Gfx i_dl_level_test1_mesh_layer_1_tri_2[];
extern Gfx mat_i_dl_grass[];
extern Gfx mat_revert_i_dl_grass[];
extern Gfx mat_i_dl_wall[];
extern Gfx mat_revert_i_dl_wall[];
extern Gfx mat_i_dl_arbre[];
extern Gfx i_dl_level_test1_mesh_layer_1[];
extern Gfx i_dl_material_revert_render_settings[];
