#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/i/leveldata.inc.c"

#include "levels/i/hoodboomer/model.inc.c"
#include "levels/i/pigpot/model.inc.c"
#include "levels/i/hoodboomer_bomb/model.inc.c"
#include "levels/i/windmill/model.inc.c"
#include "levels/i/gate/model.inc.c"
#include "levels/i/gate/collision.inc.c"
#include "levels/i/wooden_lever/model.inc.c"
#include "levels/i/plum/model.inc.c"
#include "levels/i/caged_toad/model.inc.c"
#include "levels/i/plank_rope/model.inc.c"
#include "levels/i/plank_rope/collision.inc.c"
#include "levels/i/barrier_rope/collision.inc.c"
#include "levels/i/barrier_rope/model.inc.c"