extern void scroll_i_dl_level_rocket_room_mesh_layer_5_vtx_0();
extern void scroll_i_dl_level_rocket_room_mesh_layer_5_vtx_1();
extern void scroll_i_dl_main_section_mesh_layer_5_vtx_0();
extern void scroll_i_dl_first_section_mesh_layer_5_vtx_1();
extern void scroll_i_dl_second_section_mesh_layer_1_vtx_0();
extern void scroll_i_dl_second_section_mesh_layer_5_vtx_1();
extern void scroll_i_dl_second_section_mesh_layer_5_vtx_3();
extern void scroll_i_dl_second_section_mesh_layer_5_vtx_4();
extern void scroll_i();
