#include "src/game/envfx_snow.h"

const GeoLayout i_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -10589, 43, 3050, i_dl_main_section_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, i_dl_main_section_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_ALPHA, i_dl_main_section_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -7950, 730, -1105, 90, 0, -90, i_dl_plum_bucket_mesh_layer_1),
		GEO_ASM(0, e__shotgun_effects),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 2145, 6061, -566),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout i_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, -16601, 18, -19589, -16601, -82, -19589, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, i_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, i_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, i_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, i_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
