extern const GeoLayout airlock_water_geo[];
extern Lights1 airlock_water_water_tunnel_lights;
extern u8 airlock_water_sonic_adventure_water_2_i8[];
extern u8 airlock_water_water_galaxy_i4_i4[];
extern Vtx airlock_water_airlock_water_mesh_layer_5_vtx_0[8];
extern Gfx airlock_water_airlock_water_mesh_layer_5_tri_0[];
extern Vtx airlock_water_airlock_water_mesh_layer_7_vtx_0[4];
extern Gfx airlock_water_airlock_water_mesh_layer_7_tri_0[];
extern Gfx mat_airlock_water_water_tunnel[];
extern Gfx mat_airlock_water_water_2_layer7[];
extern Gfx mat_revert_airlock_water_water_2_layer7[];
extern Gfx airlock_water_airlock_water_mesh_layer_5[];
extern Gfx airlock_water_airlock_water_mesh_layer_7[];
extern Gfx airlock_water_material_revert_render_settings[];
